### ISSUE TITLE
Slardar Immortal became too shiny/ambient

### ISSUE THREAD

**Issue by Ackerman4** [jeffhill/Dota2#1004]
### Cosmetic Item Name

Golden Fin of the First Spear

### Description

Because of the new update, the golden head immortal of Slardar became too shiny/ambient.
![Slardar Head Immortal Bug](https://user-images.githubusercontent.com/77962807/172991306-048e45ee-c912-42d8-9979-1fe882a3e4d5.png)

### Example Match ID

6608698107

**Comment by Naaveen-Kumar** [comment]
Can you please update your title accordingly?

**Comment by Ackerman4** [comment]
Thank you Devs for your hard work. Wish you all the best.
