### ISSUE TITLE
Patch 7.31D broke several of the tutorials

### ISSUE THREAD

**Issue by ExceedSC2** [jeffhill/Dota2#1005]
### Description

1. You see 3 of your name floating at the start of the game each time, and for each hero
2. In "Stuns and Disables" after stunning and killing Shadow Shaman, the tutorial doesn't move on
3. In "Roshan and the Aegis", the friendly AI doesn't help with Rosh, then afks as Jugg kills them. After killing Jugg, the tutorial doesn't move on
4. In "Invisibility and Detection" after destroying the Obs ward, and seeing the Riki "cutscene", he AI becomes inactive and he never moves over for you to continue
5. In "Glimmer Cape" the CK follows you after you glimmer and to the high ground, even if you get by him to the next part, glimmering Ogre does nothing since he doesn't move, so you can't complete it

I may have missed some, but these were the ones I couldn't complete when showing the game to my friend who is new.

**Comment by MrMooEar** [comment]
ok that's great! I went through them all and fixed them up. 👍
