### ISSUE TITLE
Dark Willow's Bedlam pierces spell immunity

### ISSUE THREAD

**Issue by Chairraider** [jeffhill/Dota2#1035]
### Ability name

Bedlam

### Description

Undocumented change from the update. 

### Example Match ID (and possibly Timestamp)

-

**Comment by LokeLok** [comment]
They fixed that with the latest update, was not suppose to be in it. Tooltip still says 'Pierces Spell Immunity: Yes. which is wrong.

**Comment by Chairraider** [comment]
thanks, fixed indeed
