### ISSUE TITLE
Killing bots in lobbies gives obscene amounts of gold

### ISSUE THREAD

**Issue by real-vaLor** [jeffhill/Dota2#1036]
### Description

Reproduction:

Create a lobby (cheats off)
Fill empty slots of enemy team only with unfair bots of any type (in this screenshot it is ranked matchmaking ai, but the same applies with default bots)
Killing bots ingame offers at least twice as much gold as it should (in this example, the bots are less than half my level, without any streak or significant networth)

![kills](https://user-images.githubusercontent.com/106837775/173111889-35a5a0a5-958d-43bd-b459-c01c1e9acf96.png)

### Example Match ID (and possibly Timestamp)

6611087977

**Comment by real-vaLor** [comment]
I went back and calculated the gold using the gold formula on dota 2 wiki for the windranger kill:

![image](https://user-images.githubusercontent.com/106837775/173113514-f7cc3636-3f0f-4277-b295-ee5a13b07e6e.png)

Windranger was level 13, with 0 kills.
The kill gold should have been 125 + 13*8 + 0 + 0 = 229

**Comment by OraCLesofFire** [comment]
"Allied heroes within 1500 radius of a killed enemy, including the killer, receive experience and unreliable gold if they assisted in the kill. To qualify for an assist, the allied hero either has to be within the given radius of the dying enemy hero, or have damaged or debuffed the enemy hero. Note that the assist counter on the scoreboard only counts assists if the player dealt damage or applied a debuff to the victim, or if they applied a buff to the killer, but gold and experience are awarded independently of the "assist" counter.

The amount of assist gold received is the same for the killer and all assisting heroes. It is calculated using the following formula:


(30 + Victim Net Worth x 0.038) x k / Number of Heroes

k = Net Worth difference factor

For leading team k = 1 - (Net Worth difference / Net Worth of leading team)

For losing team k = 1 + (Net Worth difference / Net Worth of leading team) "

Most of what you are getting is assist gold. Presumably you are playing 1v5, which means the bots will early game have a significant networth advantage over you, so the assist gold is through the roof.

**Comment by real-vaLor** [comment]
Makes sense. Was wondering where net worth came in, but I didn't know assist gold played such a large factor in kill bounty, nor that so much of it is based off of team NW difference.

This has some strange applications come to think of it: If a game has a 4 protect 1 situation (say, with a TB carry taking all of the map's farm), the extremely underfarmed rest of the team could give massive amounts of gold just based off of their TB's massive networth, resembling the behavior shown in the screenshot.
