### ISSUE TITLE
New Custom Tower Models dont have low HP crumbling animation

### ISSUE THREAD

**Issue by shaileshgarg** [jeffhill/Dota2#104]
As the tower HP lowers it has a animation where parts of the tower breaks apart, and the cracks appear. This is not present for new Custom Model

Default Tower with Crumbling animation

https://user-images.githubusercontent.com/26450759/171692501-52d28f2f-3a99-409e-ad49-81f731515723.mp4

Custom Tower with no Crumbling animation

https://user-images.githubusercontent.com/26450759/171692667-97031cf4-fe03-4573-8474-618ebbcc901e.mp4

**Comment by NMOTH** [comment]
This is not a bug. That is just the tower cosmetic animation. You can always click on the tower to see the hp % left for denying
