### ISSUE TITLE
Micro-Stutter replay

### ISSUE THREAD

**Issue by buffakee** [jeffhill/Dota2#1049]
Match ID: 6610793518

Didn't note of exact moments when it happened, but I remember it happened throughout the game. I did ask my teammates if anyone else is lagging, and they said no. They might have just not noticed, but it also could suggest the stutters were isolated to me alone.

Also my FPS was p consistent on my PC (no abnormal 1% lows), and I had 0 packet loss during the stutters.

Edit: forgot to mention I was the windranger in this game.

**Comment by BenjinZA** [comment]
Please post this in #915 and close this
