### ISSUE TITLE
PLS FIX fake Overwolf 

### ISSUE THREAD

**Issue by Parowoz23** [jeffhill/Dota2#1052]
### Description

**Description**

- Hello, my English is not good, but i would like to tell you about a bug that uses the cheat fake Overwolf, which allows you to see the last 8 games of players even with a hidden profile. You can check the difference between a fake Overwolf and a real Overwolf. Real Overwolf can't show last 8 games, but fake overwolf (cheat ) can it due the disadvantage of the game. The disadvantage of the game is that any player can view the last 8 games of each player, regardless of the settings of the public match history. This video shows everything( https://www.youtube.com/watch?v=4u7LRrSoDgc ), but in short, in the developer console, the "PlayerGamesBox" parameter is changed and the player can see the last 8 matches of any account. I find it unfair, even with a hidden match history, people using fake Overwolf can watch your matches and ban your favorite heroes. The program gives an advantage and bypasses the valve system.

**Problem**

- A cheat program calling itself "overwolf" (but its fake) allows players to view the last 8 games of accounts even with a hidden match history.

**Suggestion:**

- I'm not a programmer, just an ordinary player. However, I think that somehow it is possible to prevent players from changing parameters in the console.

### Example Match ID (and possibly Timestamp)

None

### Screenshots

![333](https://user-images.githubusercontent.com/107277064/173228291-1c4cea24-5abc-4105-8722-9571a7bd70f2.png)

https://www.youtube.com/watch?v=4u7LRrSoDgc

**Comment by jakudz4** [comment]
This needs to be fixed soon!

**Comment by K1ir** [comment]
Agreed, this is some ridiculos bs

**Comment by real-vaLor** [comment]
Agree, "real" overwolf should also be removed for being an unfair advantage (giving unfair levels of knowledge during draft phase). 
I have had my match history private for years but its unfortunate that you need to counter scumbag players that abuse it.

**Comment by Avarise831** [comment]
Cancer dota when there is a lot of things you can get from  dota client imagine if you are a cheat developer

**Comment by Daar543** [comment]
It still uses publicly available match data. Opendota will not show you a private profile, just exclude matches which were not shared. 

That means, unticking the sharing right before match will not help you, but if you play 50 games after that, the data shown will be very misleading for the "cheaters".

**Comment by Manuel-ReyGallard** [comment]
This issue was resolved with blocking User ID during the drafting phase. You can close this issue

**Comment by Parowoz23** [comment]
> This issue was resolved with blocking User ID during the drafting phase. You can close this issue

Are you seriously? Why can I still see the last 8 games? The real overwolf has been fixed, but the last 8 games in the fake overwolf are still visible.
![2323](https://user-images.githubusercontent.com/107277064/174068885-4b01ce67-78b7-40e5-a933-5738ad6c9bee.PNG)

**Comment by jeffhill** [comment]
This is out of scope - we can't use the GitHub bug list for anti-cheat stuff.
