### ISSUE TITLE
Make Ward a low priority to put in inventory slot when courier deliver with other item if slot is almost full

### ISSUE THREAD

**Issue by magnative** [jeffhill/Dota2#1057]
### Description

Example

When you already have 5 slot item and courier about deliver Observer Ward (Sentry or Bundle) and Blink Dagger (or other item)
It will put Observer ward in slot 6 and Blink Dagger in Backpack 

Which make you can't use that item right away when you in the fight.

Some other Consumable item such as Healing Salve, Clarity, Faerie Fire, Smoke of Deceit, Dust of Appearance have this issue too but I think Ward should be highest priority here since is the most purchase item.

### Example Match ID (and possibly Timestamp)

Test in All Pick Private Lobby

### Screenshots

https://user-images.githubusercontent.com/26045057/173153072-4672f171-40aa-44b2-82e2-a4a5100d2f17.mp4

**Comment by Dzanidra** [comment]
Isn't this related to the positions of the items in the courier? The item in the last slot gets delivered first. Have you tried swapping the blink and wards on the courier before delivery?

**Comment by magnative** [comment]
> Isn't this related to the positions of the items in the courier? The item in the last slot gets delivered first. Have you tried swapping the blink and wards on the courier before delivery?

I just try It and is indeed relate to position of the item in courier

I will close this issue now
