### ISSUE TITLE
a bunch of bugs that me and my friends found in the games. A BUNCH!!!

### ISSUE THREAD

**Issue by jerrymouse1995** [jeffhill/Dota2#1100]
lina
i have infused dress of the bewitching flare lv.2.
in the new update, i choose infused dress of the bewitching flare lv.2. combine with the wyrmwrought flare's light strike array special effect. however during the test, i find that the spell do work on it as it shoud be, BUT, infused dress of the bewitching flare lv.2 doesnt have the blue flare as it should be, it showed as a dress with orange flare (it feels like bewitching flare lv.2 's blue flare mixed with wyrmwrought flare's red flare).

**Comment by guianselmi** [comment]
Please report them separately so the community can vote on each of them accordingly (otherwise they all might get ignored)
