### ISSUE TITLE
Windranger Arcana BUG

### ISSUE THREAD

**Issue by Flue83** [jeffhill/Dota2#1102]
### Cosmetic Item Name

Compass of the rising gale

### Description

After 7.31d the arcana special target icon when using Focus Fire on someone doesn't show up .

### Example Match ID

6612833061

### Screenshots

![Bez tytułu](https://user-images.githubusercontent.com/107299714/173195614-1e2192ac-b3bc-489c-b3ec-2cf051c52055.jpg)

**Comment by Aluerie** [comment]
might be related to Jeff starting work on #21 but definitely upvote ;

Also Arcana WR uses base hero arrows for Focus Fire 
![image](https://user-images.githubusercontent.com/33165440/173196275-b83afe3b-df8d-4bbc-b683-0fe36a10b6e2.png)

while arcana arrows are also marine coloured.
![image](https://user-images.githubusercontent.com/33165440/173196318-224a4efd-4cb6-4f17-8483-2b095492e9fb.png)

**Comment by b573708832** [comment]
![ABA68362-FE4B-4FE3-9B48-4FEDB7984113](https://user-images.githubusercontent.com/80692499/175274950-4c002279-9ccb-4229-bf13-13f30532c725.jpeg)
![C9C5BCF5-7C74-4BF4-BEA0-0987EBF07692](https://user-images.githubusercontent.com/80692499/175274965-7100ec20-c77e-4534-a43c-f9102535ebf9.jpeg)
Icons like these

**Comment by cameron-valve** [comment]
Fix for this should go out tomorrow!
