### ISSUE TITLE
axe aghanim bugged 

### ISSUE THREAD

**Issue by Misky11** [jeffhill/Dota2#1121]
### Item name

aghanim on axe

### Description

when i bought aghanim its said that will give 7 armor but its actually giving 3 armor and reducing 3 armor as well i think this bugs happened after 7.31d.you can check screenshot as well
![20220612020852_1](https://user-images.githubusercontent.com/107326195/173205948-ed33d802-c7ac-4253-a2e1-c318a03e9833.jpg)
![20220612020931_1](https://user-images.githubusercontent.com/107326195/173205949-c350e8d7-ee87-45aa-98d5-a220df4ec621.jpg)
![20220612020935_1](https://user-images.githubusercontent.com/107326195/173205951-98082873-273b-4a04-adb8-c34981fb4d50.jpg)

i checked this in demo as well and it will reduce 3 armor from enemy and increase 3 armor for axe per target

### Example Match ID and Timestamp

6613293619 - 36:45

**Comment by TheUnholyWrath** [comment]
An armor change of 7 includes your gain and their loss; you are gaining 3.5 armor and they lose 3.5 armor. Gaining and reducing 7 armor sounds pretty imbalanced so its likely working correctly. You should close this

**Comment by Misky11** [comment]
Reduces  [Berserker's Call](https://dota2.fandom.com/wiki/Axe#Berserker.27s_Call) cooldown by 2 seconds and causes it to apply  [Battle Hunger](https://dota2.fandom.com/wiki/Axe#Battle_Hunger) on affected enemies. Causes  [Battle Hunger](https://dota2.fandom.com/wiki/Axe#Battle_Hunger) to reduce the enemy's armor by 7 and grant 7 armor to Axe per affected enemy, values halved for creeps.
