### ISSUE TITLE
Axe is muted even those ther is nothing used on him that cloud mute him

### ISSUE THREAD

**Issue by JaydeepGo** [jeffhill/Dota2#1144]
### Description

I have checked all the statuses but no one should mute axe. 

### Example Match ID (and possibly Timestamp)

6614125771 - 40:24

### Screenshots

![image](https://user-images.githubusercontent.com/29326238/173229627-7b05f701-3c6b-4bc6-a758-a16bcfc0155d.png)

**Comment by ExplodedCow** [comment]
Silencer has a Lv25 talent that causes Last Word to mute as well as silence. He had it here.

**Comment by JaydeepGo** [comment]
Ohh My Bad. Closing the Issue.
