### ISSUE TITLE
+70 MMR on wins?

### ISSUE THREAD

**Issue by Ackerman4** [jeffhill/Dota2#1155]
### Description

Hi, I think this is the 3rd or 4th time after the update where I won a game and I received another +70MMR. I'm not quite sure how did this happened. However, when I lose, I only receive a -30MMR. I want to know if this is a bug or is actually the MMR system on my bracket. Before the update, I only receive +30MMR on wins, and -30MMR on losses. I'm only Archon though. Thank you.

### Example Match ID (and possibly Timestamp)

6614463727

**Comment by ZZalles11** [comment]
How consistently does this happen? If it only occurs after winstreaks, it could be the smurf detection system. If it's random, that's stranger.

**Comment by Ackerman4** [comment]
I'm not smurfing though, this is my main account. Also, a couple of days before the update, I was able to have a 7 winstreak, and then I received 2-4 losses and then the game updated. Then I noticed that the percentage of my medal is somewhat strange, it gets higher than usual when I receive a win.

**Comment by Ackerman4** [comment]
Also, I think this just happened for about 2-4 winning games I think? Because I immediately noticed how fast I climbed from Archon 1 to Archon 2 even though I have lots of loss to compensate with winning games.
Now I just played with my friends, 5 man party, we won, and I was able to receive +70MMR.

**Comment by Ackerman4** [comment]
I just read the smurf detection on reddit dota 2. Hmmm I can't say that I am really skilled enough to climb a higher rank. 😅
Maybe I'll just monitor my games again for now. 
I just posted this because I got so frightened that my account might get banned and I have spent lots of money on this account to buy stuff. 😅
Will close this issue for now.
