### ISSUE TITLE
[Ability Draft] Torrent Storm is not awarded

### ISSUE THREAD

**Issue by UnpopularOpinion** [jeffhill/Dota2#1161]
### Description

Torrent Storm is not awarded after purchasing Aghanims Scepter despite tool tip saying so for the Torrent skill

![image](https://user-images.githubusercontent.com/48537975/173239700-627b368c-7d25-4805-b9bf-641b879f9dd1.png)
![image](https://user-images.githubusercontent.com/48537975/173239709-4cfd2441-6558-463c-bb7c-7462c14a1647.png)

### Example Match ID (and possibly Timestamp)

6614641592 - 30:09 above

**Comment by ZZalles11** [comment]
Did you check and make sure that toggling auto-cast on torrent (right clicking the spell) didn't give torrent storm? It doesn't give as a separate ability intentionally.

**Comment by zaxer2** [comment]
Torrent Storm is accessed by toggling auto-cast on Torrent. Please delete this, and read the tooltip next time.

**Comment by UnpopularOpinion** [comment]
> Did you check and make sure that toggling auto-cast on torrent (right clicking the spell) didn't give torrent storm? It doesn't give as a separate ability intentionally.

whoops didn't see that small part. thanks for the info. closing this issue.
