### ISSUE TITLE
Cheaters in the games

### ISSUE THREAD

**Issue by techforces** [jeffhill/Dota2#1174]
### Description

Hi, I have played a game with a cheater recently and made a post about it with clear evidence on Reddit but a moderator there deleted it without stating any reason. This is the only place I know where I can submit the issue, I apologize if it is an incorrect place.

Cheater: Skywrath Mage
https://user-images.githubusercontent.com/61235723/173248275-4313cc6c-9dd8-49f7-b4e9-06fbd5c93210.mp4

- Sky has no vision on jug in this clip for a long period, yet knows his exact location while farming the camps and jumps into no vision.
- Weird camera and cursor interaction. Unnatural zooms, cursor and selected move point do not match.
- Suspected autohex (hard to prove).

### Example Match ID (and possibly Timestamp)

6614812617 - 36:28

**Comment by ZZalles11** [comment]
Neither this nor reddit is really the location. The route for reporting cheaters is overwatch or steam reports.
