### ISSUE TITLE
When casting, edge pan and arrow keys do not work

### ISSUE THREAD

**Issue by ZZalles11** [jeffhill/Dota2#1178]
### Description

Probably related to this issue: https://github.com/jeffhill/Dota2/issues/940 but differs because this is unrelated to having assisted camera on.

When spectating as a caster, some clicks will lock the camera regardless of whether assisted camera is turned on or off. When this occurs, edge pan and arrow keys will not work **unless** you specifically pan to a corner or press two arrow keys at once. This unlocks the camera until the spectator clicks again. Sometimes, this leads to camera getting stuck panning off to one side until the freeing action is done. Behavior persists across restarts, and across many possibly related setting changes.

This has happened twice on two days in two different ticketed lobbies. However, could not reproduce again immediately after in a private lobby. Attached link at timestamp shows the scrolling behavior, and stream shows many examples of the edge pan failing. 

### Example Match ID (and possibly Timestamp)

https://www.twitch.tv/videos/1499527594?t=00h14m49s

**Comment by eddieparker** [comment]
This should be fixed in the next update. Thanks for the information!

**Comment by ZZalles11** [comment]
@eddieparker thank you!
