### ISSUE TITLE
Sticky bomb gives vision of target for much longer than expected if thrown during teleport

### ISSUE THREAD

**Issue by w8eight** [jeffhill/Dota2#1227]
### Ability name

Sticky Bomb

### Description

I noticed this bug during ability draft, however I believe it's ability related, and not tied to particular game mode.

If someone throws a sticky bomb at the teleporting target, and bomb doesn't reach the target before the tp channelling is complete, sticky bomb will, well stick. But for much longer than expected. And it will give vision to the team that has thrown the bomb. 
Eventually it explode (after hero it stick into cast a spell).

Link to the clip showing the issue:
https://drive.google.com/file/d/1RItL-xr8O0djdB2xERBZ6Fkg9ZGNKE6E/view?usp=sharing

### Example Match ID (and possibly Timestamp)

6616595400

**Comment by w8eight** [comment]
> Possibly related/duplicate of #661

Definitely related, but in original clip, bomb does explode right away.

**Comment by BenjinZA** [comment]
Do you mean the video on the linked issue? Watch the Sticky Bomb thrown at 00:17 video time. It doesn't explode.

**Comment by w8eight** [comment]
Ah yes, my bad. I watched only first example.  I am closing the issue, as duplicate is better written
