### ISSUE TITLE
Midas Knuckles No Custom Effect

### ISSUE THREAD

**Issue by shaileshgarg** [jeffhill/Dota2#1229]
### Cosmetic Item Name

[Razzil's]Midas Knuckles

### Description

The immortal doesn't have the Last Hit  Effect anymore.

No Extra Gold Coins on Last Hitting

https://user-images.githubusercontent.com/26450759/173623360-d2e2170b-06d2-4876-a66b-41fb31a84275.mp4

https://dota2.fandom.com/wiki/Midas_Knuckles, what it looked like.

### Example Match ID

-

**Comment by Astiberon** [comment]
This is a demo bug. In a normal game, the effect is present. Please close the topic.
![image](https://user-images.githubusercontent.com/107125193/173684777-2ff5f18f-df6a-4978-bd33-371f8d545c08.png)
