### ISSUE TITLE
 How an overwolf watches your games, even if they are hidden from you.

### ISSUE THREAD

**Issue by Losantes** [jeffhill/Dota2#1243]
### Description

Hello Jeff. In general, I recently wrote about the overwolf (cheat), they downvoted me, they didn’t believe me, but here you can set the -dev parameter in the game itself and see the hidden parameters by simply changing the parameters visibility: collapse ; on visibility: visible.
Please fix this, it's impossible to play your favorite hero after a 3 game win streak.

### Screenshots

![image](https://user-images.githubusercontent.com/83698029/173695053-b4e9b82e-00ee-48e7-8c8f-29ede63a0aab.png)

**Comment by Losantes** [comment]
Also, during the battle pass, you can watch the paths of the catacombs (heroes, not rewards)

**Comment by jeffhill** [comment]
This is out of scope - we can't use the GitHub bug list for anti-cheat stuff.
