### ISSUE TITLE
[Quality of Life- Suggestion] An Option to disable 'tips' from Enemy team.

### ISSUE THREAD

**Issue by GauravDe-git** [jeffhill/Dota2#1256]
### Description

The Dota 2 'tips' system was added to the game as a way to encourage players when they played well by tipping them. But despite that players have managed to find out a way to use it as a BM tip/ toxic tip. 

I feel that just like there is an option to mute your enemy, there should be an option to disable 'tips' from the enemy team because an enemy tipping 99% is to be toxic, and does not appreciate or encourage your plays.

**Comment by shaswatag4** [comment]
XD

**Comment by Soubhikkk** [comment]
🙂🙂

**Comment by kaveenkumar** [comment]
where is the fun in that?

**Comment by kaveenkumar** [comment]
remove tips, remove stickers, remove all-chat voice lines > then basically DoTA becomes LoL > then complain DoTA copies from LoL

**Comment by pontuslaestadius** [comment]
This isn't a bug, please close it.

**Comment by GauravDe-git** [comment]
Ok lets just enjoy bm tips till the end of time ^_^
