### ISSUE TITLE
[suggestion] Let us buy report slots with shards/split smurf and behavior reports

### ISSUE THREAD

**Issue by prohjort** [jeffhill/Dota2#1259]
As someone who mostly play in a party of 3+, i barely have to avoid players. However, the amount of smurfs we play against in the archon bracket is insane. At the moment, all my reports are gone after a few games, and i'm not able to report players who are actually toxic, since i have to prioritize what i use my reports on, and have decided to spend them on people smurfing since toxic people can get muted by a player. 

5 max reports in archon can be gone in 2-3 games on a bad day.

(The players in my party all got 5k+ games and perfect behavior score, so in theory we shouldn't get matched against smurfs)

**Comment by Krev5** [comment]
Don't agree on purchasing part, but there should really be no limitation to smurd reporting. The actual smurfs will be getting significantly more reports than a default user so the system would have much trouble understanding

**Comment by Daar543** [comment]
Doesn't smurf report cost you no charges?
