### ISSUE TITLE
QOL: Aghanim's Shard should always be delivered by the courier into your inventory first since it is instantly consumed (to avoid full inventory issues)

### ISSUE THREAD

**Issue by Big-Mudd** [jeffhill/Dota2#127]
### Description

Since Agh's Shard is automatically consumed upon entering your inventory, if it was always delivered first, this would help avoid scenarios where it remained on the courier due to a full inventory. 

Ex: if you only have 3 free inventory slots, but have 4 items being delivered and one of them is Agh's Shard, this should never result in items failing to be delivered as the shard does not ultimately take up an inventory slot. If it was delivered first, it would instantly be consumed making space for the other 3 items.

Alternative solution: It should be delivered directly to its dedicated "slot" and never enter your inventory in the first place.

**Comment by arkhanov** [comment]
Can couriers pick up shards from rosh?

**Comment by Nathanael-Valve** [comment]
Will be fixed in the next update. A courier carrying a shard and told to transfer items to you will, if you don't have a shard, always result in you consuming the shard regardless of your inventory situation.
