### ISSUE TITLE
The All Hero Challenge list is cut off

### ISSUE THREAD

**Issue by Forrest7778** [jeffhill/Dota2#1272]
### Description

The All Hero Challenge list is cut off at the bottom and you can only see the top part of the hero portraits, it's a VERY VERY VERY minor thing, but thought it was worth mentioning as you can't scroll down to see them and can only barely put your cursor over them to reveal them 

### Screenshots

https://i.imgur.com/F0Xqjb4.png

**Comment by gamma032steam** [comment]
Duplicate of https://github.com/jeffhill/Dota2/issues/420?

**Comment by Forrest7778** [comment]
@gamma032steam Correct, it's a duplicate. Apologies and closing.

**Comment by gamma032steam** [comment]
No stress, hope it gets fixed!
