### ISSUE TITLE
Please make hero walk to unit on right click instead of trying to attack it when its hp is above deny threshold when you have "force right click to attack" ON

### ISSUE THREAD

**Issue by kapsnik** [jeffhill/Dota2#1276]
### Description

Currently what's happening is that if you right click some unit that has non-deniable hp, your hero will just stop and stay still. It will be much better to make heroes just walk to units if their hp is above deny thrershold. It's probably not even a bug, but if that will be changed it will be really good, because I myself lost several games due to it.

### Screenshots

https://user-images.githubusercontent.com/92246079/173838072-0d478262-a8a0-4217-91c8-61bbcdb04caf.mp4

**Comment by gamma032steam** [comment]
For reference, I believe this issue is referring to `Right-Click to Force Attack` under `Options` in the settings menu.

I can't think of any reason why this shouldn't be done as a quality of life change. Could there be any implications?

**Comment by Aluerie** [comment]
duplicate for #238 

Please, close your issue and upvote+comment extra details in linked one.
