### ISSUE TITLE
Kotl not facing the correct way when casting illuminate

### ISSUE THREAD

**Issue by cynicuL** [jeffhill/Dota2#13]
While KotL is under the affect of his ultimate, the double left in his place to cast illuminate doesn't face the way illuminate is casted, instead it faces the way keeper of the light was facing when pressing the key.

**Comment by bronnerjoji** [comment]
Correct me if I'm wrong but I believe this bug didn't appear until like 7.31 (or maybe 7.30). I remember Illuminate working correctly in Spirit Form previously so it maybe helpful looking at the source code before the recent patches.

**Comment by cynicuL** [comment]
I believe the bug came about as a result of adding a cast point to illuminate

**Comment by jeffhill** [comment]
This will be fixed in the next hotfix, likely later today.
