### ISSUE TITLE
Enter a short summary here!

### ISSUE THREAD

**Issue by Such1es** [jeffhill/Dota2#1313]
### Ability name

Windranger Focus Fire

### Description

Forgive me in advance for my English, I don't know it very well, I have to use a **translator**.

Now it doesn't work the way it used to. Previously, after using it, you always started hitting the hero as he was in the attack radius even after blink, doppelganger or manta style. Now that's not the case. Now after the things I wrote above, you need to either click attack the hero again, or click under yourself.
Now windranger can be wiped with a manta style for itself and it will stop beating for a moment. As well as the phantom Lancer, whom she killed, will now be able to kill her.
And it happened after the exit of the Labyrinth of Aganim part 2

### Example Match ID (and possibly Timestamp)

This happens in every game with illusionists or Manta Style, and there is a video of what is happening on Reddit

**Comment by Aluerie** [comment]
it is duplicate #21 

Even more, JeffHill already fixed it ; so can you provide any match ids/ footage on after ~10h ago client update
