### ISSUE TITLE
Static Link movement bug

### ISSUE THREAD

**Issue by Makakass** [jeffhill/Dota2#1325]
### Ability name

Static Link + Focus Fire

### Description

1. Use static link -> start moving -> something happens that forbids you to attack (Target: invisibility, astral, dissimilate, bane sleep, etc; Razor: halberd, etc), then Razor stops auto-attacking during Static Link even after these effects end. You have to stop moving to fix this. Focus Fire have same behavior btw.

2. Related so I don't want to separate: now Razor can't cancel Static Link auto-attack with hold button (at the same time hold button works for Focus Fire although it's a similar mechanic). It's related because experienced razor players start moving in the first second of bane sleep to stop hits, so if you will fix the first bug, but not this one, it can affect the game balance.

### Example Match ID (and possibly Timestamp)

-

**Comment by Makakass** [comment]
Important my previous static link issue: https://github.com/jeffhill/Dota2/issues/1324
Also a annoying bug: https://github.com/jeffhill/Dota2/issues/89

**Comment by 77AD77** [comment]
To add more you don't need any target your attack will cancel/stop if ( Right-click mouse) command is used on the ground before the first attack from Static Link.

Before the bug, Static Link used to always hit the linked target back so if you tried to hit other targets using (Attack) command it will hit one time and go back to the Static link target. 

Eye of the storm Razor ultimate with this bug can easily deceive the player, especially in a team fight or beside any creep.

**Comment by Makakass** [comment]
Fixed today
