### ISSUE TITLE
Overthrow shop missing newer items

### ISSUE THREAD

**Issue by kekowil** [jeffhill/Dota2#1343]
### Description

Since Overthrow is available in weekend rotations, the shop should be updated to include newer items that have been added since the mode was last updated. For example, items such as Aghanim's shard can only be found by searching by name.

**Comment by Nathanael-Valve** [comment]
There's a partial update to the shop in this update, more updates will come later.

**Comment by Nathanael-Valve** [comment]
Shipping second update.
