### ISSUE TITLE
Necrophos heartstopper aura pierces spell immunity, but it shouldn't

### ISSUE THREAD

**Issue by Masedko** [jeffhill/Dota2#1347]
### Hero and spell

Heartstopper aura

### Description

Necrophos heartstopper aura pierces spell immunity, but it shouldn't. [Video example](https://youtu.be/iEKYf_shECU

### Screenshots

![Снимок](https://user-images.githubusercontent.com/78966998/174271331-a10b87af-ab1a-47db-a2f6-82ef3c5a8276.PNG)

**Comment by shaileshgarg** [comment]
#634
