### ISSUE TITLE
[BUG] Infinite guild contracts with overthrow trios (current weekend spotlight)

### ISSUE THREAD

**Issue by heywood8** [jeffhill/Dota2#1350]
### Description

Guild contract can be accomplished with "Overthrow trios" game mode.
Usually, when you complete a contract, it is marked as "done" and disabled until next day.
When playing Overthrow it is not disabled after a win and accomplishing contract.
On consequent games Guild Points are also added, so not a visual only bug.

This might be a loophole for some guilds to farm guild points 

No Dota plus 

### Example Match ID (and possibly Timestamp)

6622002865, 6622020891 (IO, BH)

**Comment by Nathanael-Valve** [comment]
Shipped a speculative fix. Please comment here if it recurs.

**Comment by heywood8** [comment]
@Nathanael-Valve 
> Shipped a speculative fix. Please comment here if it recurs.

Contract still not disabled after completing and winning in overthrow.
Trying to win again to confirm that's not a visual bug

**Comment by heywood8** [comment]
Confirming that the visual bug still persists.
What was the fix particularly? Is overthrow not supposed to complete contracts at all?
If it is not, it still shows that contract is completed, however GP are not added

**Comment by Nathanael-Valve** [comment]
Thanks for getting back to me on this! We're evaluating contracts for these short modes. As to the visual bug, yes, that seemed to be because the server and the coordinator disagreed on the validity of the contract, and the server was telling the postgame on the client what to display. That should be fixed going forward.
