### ISSUE TITLE
crush game w/o errors

### ISSUE THREAD

**Issue by NighTSell** [jeffhill/Dota2#1362]
### Description

Crush game on processor AMD with integrated graphics after a short period of time after start game

**Comment by FazyDota** [comment]
Please, provide more detail and consider renaming the ticket to be more descriptive.

What are your specs, what is your OS etc etc.

**Comment by NighTSell** [comment]
![image](https://user-images.githubusercontent.com/107699689/174346032-a0bea183-2e84-429d-a339-ff86b7c42e2a.png)
![image](https://user-images.githubusercontent.com/107699689/174346079-3b3311c4-f2c6-4072-b88c-733c8057f32e.png)
![image](https://user-images.githubusercontent.com/107699689/174346102-d81b390c-87e4-44fe-8a6a-257d3ad49a4e.png)
![image](https://user-images.githubusercontent.com/107699689/174346130-82711140-d1fc-4d82-925f-c3e3f477399c.png)
