### ISSUE TITLE
Can't TP

### ISSUE THREAD

**Issue by razmanzaidi** [jeffhill/Dota2#1382]
I don't know what's going on but since the update about 30 mins ago I can't press TP or dawnbreaker ulti unless i spam it, same issue reported by other players in game

**Comment by Tenk4** [comment]
same here

**Comment by Tugsuse** [comment]
Same here. Cant use MK's wukong, and primal spring.  Cannot TP.  Cannot use Dawn's ulti etc

**Comment by BulaLonG420** [comment]
If tried to tp and the wukong primal spring. Apparently they all need to be activated by a right click first before u can use.

**Comment by BulaLonG420** [comment]
Also the magnus skewers when casted he is stuck in one place.

**Comment by hzhao97** [comment]
cant tp as well, unless i walk out of base or give a command other than tp like use tango or ward

**Comment by NemmyC** [comment]
Match 6623261045
Many people had this issue during this match including me.
Tp didn't work unless I tried 4-5 times and never when using the minimap to tp.

**Comment by Losantes** [comment]
ye my team too cant tp

**Comment by Krev5** [comment]
+
