### ISSUE TITLE
Monkey King cannot Primal Spring

### ISSUE THREAD

**Issue by luckytaurus11** [jeffhill/Dota2#1384]
### Ability name

Primal Spring

### Description

Casting Primal Spring works 10% of the time or less... don't have a clue why it works some times and not others. But this hero is currently unplayable.

### Example Match ID (and possibly Timestamp)

6623248899

**Comment by luckytaurus11** [comment]
i think it's now fixed?

**Comment by yckmm** [comment]
This has been fixed, please close.

**Comment by luckytaurus11** [comment]
Fixed soon after
