### ISSUE TITLE
Casting Spell Bugs & Teleportation

### ISSUE THREAD

**Issue by BulaLonG420** [jeffhill/Dota2#1387]
### Ability name

Primal Spring, Skewer, Teleportation

### Description

Teleport casting bugs
Primal spring cannot cast.
Casting skewer makes magnus hero model be static in the cast point (walking animation but not moving in the place) 

All of the bugs mentioned requires a trigger to properly casted. (For me, right clicking the moment before u cast a spell is the trigger)

6:32-7:12 - TP Bug
8:43-9:01 - TP Bug
9:20-9:38 - Primal Spring Bug
25:57-26:15 - Skewer Bug

![image](https://user-images.githubusercontent.com/107027411/174423757-e5b96036-e0b3-4ce4-8ff4-e983241917f9.png)
![image](https://user-images.githubusercontent.com/107027411/174423762-77c0d0e2-1062-46de-a9f3-45151f882c55.png)
![image](https://user-images.githubusercontent.com/107027411/174423801-44ea7757-8f45-4078-b0db-6d718b716663.png)
![image](https://user-images.githubusercontent.com/107027411/174423808-faf0411a-cd3c-467c-b020-bce3157fc44a.png)
![image](https://user-images.githubusercontent.com/107027411/174423815-7b8973f3-5a76-4e1b-ad06-4817db5da8ca.png)

### Example Match ID (and possibly Timestamp)

6623255246 - 6:32-7:12; 8:43-9:01; 9:20-9:38; 25:57-26:15

**Comment by deleted1313** [comment]
same here, also sometimes cant use ball lightning when playing storm spirit

**Comment by The-Senate** [comment]
I played a game as Jakiro earlier and had all the same problems. Issues TPing out of base (had to leave fountain area to start the TP). Issues casting all spells at one point or another, and issues using items (Veil of Discord)
