### ISSUE TITLE
cant play on pudge

### ISSUE THREAD

**Issue by DeadPANK** [jeffhill/Dota2#1424]
### Description

pudge alvays in ban or he go in ban on 1 pick, plz make him unban and who pick pudge 1 hi play on pudge

### Example Match ID (and possibly Timestamp)

1

**Comment by SoumyajitKarmakar** [comment]
Can we ban such people ?

**Comment by DeadPANK** [comment]
> Can we ban such people ?

lol why, its serios bug. many patch ago valve add avtoban popular heros, and pudge its top 1 popular hero in history of dota, but avtoban + players ban + ban if 2 pick pudge = 1 game on pudge in month this is not ok
