### ISSUE TITLE
Fiend's Gate can be destroyed by Exorcism + animation bug.

### ISSUE THREAD

**Issue by MisterFlicker** [jeffhill/Dota2#1429]
### Ability name

Fiend's Gate

### Description

Fiend's Gate is not a building or unit that can be targeted for destruction. However, Fiend's Gate can be destroyed by Exorcism (Death Prophet). Exorcism is spell. Fiend's Gate is spell immune (for example Diabolic Edict can't destroy Fiend's Gate). I'm not sure that this mechanic is correct, i think Fiend's Gate should not be destroyed.

I also want to note that the Fiend's Gate destruction animation is the same as the destruction animation of Tombstone (Undying).

https://user-images.githubusercontent.com/106338856/174502192-573c6fd8-5dd6-4f45-93d5-bce66d9f5ee0.mp4

### Example Match ID (and possibly Timestamp)

No ID

**Comment by shaileshgarg** [comment]
#1280
