### ISSUE TITLE
Smurfers and behavior system

### ISSUE THREAD

**Issue by Loc-Dawg** [jeffhill/Dota2#1440]
### Description

Hello, Jeff Hill I think there is need to rework behavior system especially reports. I have question how smurfers and accbuyers with 1-40 levels suppose to report other players just because they want it. I was just chilling turbo playing for fun and then smurfer or idk who he is with 2 lvl in dota profile just reported me after the game and he destroyed my behavior score, I think that doesnt seem fair. Even if imagine that man with 2 level dota is just newbie why he can report anyone he want, he doesn't seem to understand the whole game particularly in turbo, just because he doesnt like me.

### Example Match ID (and possibly Timestamp)

6627002647

### Screenshots

![behavior](https://user-images.githubusercontent.com/107857110/174596589-581652b0-fb17-43e6-80b3-1028a5c0b3c6.png)

**Comment by SnabrielSnarsch** [comment]
this issue is out of scope
