### ISSUE TITLE
Dark willow not affected by Mar's God's rebuke

### ISSUE THREAD

**Issue by cashwathkumar** [jeffhill/Dota2#1448]
Dark willow takes no damage from God's rebuke when in shadow realm although is affected by slow. This interaction inconsistent from other physical damage aoe abilities like bristle back's quill spray.

**Comment by Aluerie** [comment]
this is mentioned in #1241 as one of abilities having this weird interaction so it's a duplicate

Please, close your issue, upvote + comment extra details if any in linked post instead.
