### ISSUE TITLE
linken sphere bug

### ISSUE THREAD

**Issue by nvidiaraytracing** [jeffhill/Dota2#1449]
### Item name

linken sphere

### Description

linken sphere is not working as it should, so even though the countdown timer is still running, it still works.
So the linken sphere works 2 times while the countdown timer is still running which should only work once.

https://user-images.githubusercontent.com/107874324/174650716-ec2dabe8-dfc8-463b-beec-f82a5ba065e8.mp4

https://user-images.githubusercontent.com/107874324/174651861-4d5888c4-e3e9-4b5d-baab-fa13594c5a12.mp4

https://user-images.githubusercontent.com/107874324/174650828-4c613844-7c8e-437c-a46d-3b47ffe6bea1.mp4

https://user-images.githubusercontent.com/107874324/174650994-4f6ece79-b799-4daa-b89d-6272119898d0.mp4

### Example Match ID and Timestamp

6627269093 - 20/6/2022 21:21

**Comment by SnabrielSnarsch** [comment]
Dude.....qop have the spell block talent
it works like a linkens
