### ISSUE TITLE
Windranger movement will glitch during ult if enemy is out of attack range.

### ISSUE THREAD

**Issue by bclaw524** [jeffhill/Dota2#1476]
Match ID: 6627449479, around 12:50~13:10 in the mid lane

WR kept trying to move and still chase after the Tiny I ulted, even though he was out of my attack range and I was trying to move away (towards the radiant Jungle)

**Comment by Aluerie** [comment]
oh wow, that's interesting, 

but please, can you post this as comment in #21 and close this issue 

we are kinda on fire with wr R in that post :D

**Comment by bclaw524** [comment]
@Aluerie 

Ok, will do.
