### ISSUE TITLE
You cannot ping items on your own courier while it is dead

### ISSUE THREAD

**Issue by PowaHouse** [jeffhill/Dota2#148]
### Description

https://www.reddit.com/r/DotA2/comments/uzmxw4/you_cannot_ping_items_on_your_own_courier_while/

**Comment by NMOTH** [comment]
I believe this is intended. They disabled all pinging when a unit is dead to reduce the in game "toxicity".

**Comment by PowaHouse** [comment]
> I believe this is intended. They disabled all pinging when a unit is dead to reduce the in game "toxicity".

Still an exception could be made to pinging your own courier, that is useful when your courier dies with an important item inside of it like blink dagger.

**Comment by arkhanov** [comment]
> I believe this is intended. They disabled all pinging when a unit is dead to reduce the in game "toxicity".

Why though? If my courier dies with bkb rectipe, i should be able to ping it and let my allies know something like 'bkb on courier (dead for 2:13)'

**Comment by loocyi** [comment]
> I believe this is intended. They disabled all pinging when a unit is dead to reduce the in game "toxicity".

Stop flaming your courier bro. 😆

**Comment by cameron-valve** [comment]
This is fixed and should go out in the next update.  @arkhanov, the new ability ping message will indicate that your item is on a dead courier and how long it will be until it respawns, thanks for that suggestion!

You can also only do this for your own courier. Attempting to ping items on an ally's dead courier will give an error (just like pinging an item on a dead ally's inventory).

**Comment by PowaHouse** [comment]
@cameron-valve Thank you
