### ISSUE TITLE
Pudge hook on runes bugged

### ISSUE THREAD

**Issue by Stephanie55** [jeffhill/Dota2#1486]
### Ability name

Pudge hook

### Description

Hook has a search radius of 100, but it's not working on runes. I noticed it while watching No[o]ne playing pudge. He tried to hook a haste rune and the pudge said "it's the little things, you know" which is a chat wheel arcana pudge has when he hooks rune. But he didn't actually catch it.
I also tested it in a lobby. I created a hero and in console I made a 100 radius circle around him. I placed him slightly further to the pudge than the rune. I hooked and I caught the hero. I then threw another hook to get the rune. Pudge made a response as if I caught the rune and the hook even gave vision (hook only gives vision if you catch something). But I didn't actually catch the rune.

https://user-images.githubusercontent.com/40859719/174900886-a4649e3c-0be6-4f97-9d55-e1cb8849e2d7.mp4

### Example Match ID (and possibly Timestamp)

6626410053 - 20:08

**Comment by opomuc** [comment]
Looks like a duplicate of #663. 
@Stephanie55 you can close this issues. And give thumbs up to #663 to promote it

**Comment by Stephanie55** [comment]
This issue is the same as issue #663. Closing duplicate.

**Comment by derekks** [comment]
cool
