### ISSUE TITLE
Disable ally help inconsistency

### ISSUE THREAD

**Issue by Anomaluna** [jeffhill/Dota2#15]
<html>
<body>
<div data-reddit-rtjson="{&quot;entityMap&quot;:{},&quot;blocks&quot;:[{&quot;key&quot;:&quot;5150g&quot;,&quot;text&quot;:&quot;There is an inconsistency with which single-target friendly spells and items can or cannot get disabled by turning off ally help.&quot;,&quot;type&quot;:&quot;unstyled&quot;,&quot;inlineStyleRanges&quot;:[{&quot;offset&quot;:107,&quot;length&quot;:21,&quot;style&quot;:&quot;BOLD&quot;}],&quot;entityRanges&quot;:[],&quot;data&quot;:{}},{&quot;key&quot;:&quot;65vc2&quot;,&quot;text&quot;:&quot;Can be disabled&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:0,&quot;rowIndex&quot;:0}},{&quot;key&quot;:&quot;81gdt&quot;,&quot;text&quot;:&quot;Cannot be disabled&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:1,&quot;rowIndex&quot;:0}},{&quot;key&quot;:&quot;6c7c9&quot;,&quot;text&quot;:&quot;Force Staff/Hurricane Pike&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:0,&quot;rowIndex&quot;:1}},{&quot;key&quot;:&quot;4st41&quot;,&quot;text&quot;:&quot;Wind Waker (Pierces BKB)&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:1,&quot;rowIndex&quot;:1}},{&quot;key&quot;:&quot;2boii&quot;,&quot;text&quot;:&quot;Bane Nightmare&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:0,&quot;rowIndex&quot;:2}},{&quot;key&quot;:&quot;11oa6&quot;,&quot;text&quot;:&quot;Vengeful Spirit Nether Swap&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:1,&quot;rowIndex&quot;:2}},{&quot;key&quot;:&quot;6mgsi&quot;,&quot;text&quot;:&quot;Keeper of the Light Recall&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:0,&quot;rowIndex&quot;:3}},{&quot;key&quot;:&quot;fpti7&quot;,&quot;text&quot;:&quot;Pudge Dismember (Agh&#39;s Shard)&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:1,&quot;rowIndex&quot;:3}},{&quot;key&quot;:&quot;1kevh&quot;,&quot;text&quot;:&quot;Snapfire Gobble Up (Agh&#39;s Scepter)&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:0,&quot;rowIndex&quot;:4}},{&quot;key&quot;:&quot;1eun7&quot;,&quot;text&quot;:&quot;Dark Seer Ion Shell&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:1,&quot;rowIndex&quot;:4}},{&quot;key&quot;:&quot;dmfa9&quot;,&quot;text&quot;:&quot;Snapfire Firesnap Cookie&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:0,&quot;rowIndex&quot;:5}},{&quot;key&quot;:&quot;5kshq&quot;,&quot;text&quot;:&quot;Earth Spirit Enchant Remnant (Agh&#39;s Scepter)&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:1,&quot;rowIndex&quot;:5}},{&quot;key&quot;:&quot;7glqj&quot;,&quot;text&quot;:&quot;Earth Spirit Boulder Smash&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:0,&quot;rowIndex&quot;:6}},{&quot;key&quot;:&quot;9afgb&quot;,&quot;text&quot;:&quot;Earth Spirit Geomagnetic Grip (Talent)&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:1,&quot;rowIndex&quot;:6}},{&quot;key&quot;:&quot;1kshv&quot;,&quot;text&quot;:&quot;Winter Wyvern Cold Embrace&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:0,&quot;rowIndex&quot;:7}},{&quot;key&quot;:&quot;a43au&quot;,&quot;text&quot;:&quot;Rubick Telekinesis (Agh&#39;s Shard)&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:1,&quot;rowIndex&quot;:7}},{&quot;key&quot;:&quot;bbms2&quot;,&quot;text&quot;:&quot;Kunkka X Marks The Spot&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:0,&quot;rowIndex&quot;:8}},{&quot;key&quot;:&quot;6sagk&quot;,&quot;text&quot;:&quot;Phoenix Supernova (Agh&#39;s Scepter)&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:1,&quot;rowIndex&quot;:8}},{&quot;key&quot;:&quot;vd87&quot;,&quot;text&quot;:&quot;IO Relocate&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:0,&quot;rowIndex&quot;:9}},{&quot;key&quot;:&quot;dlfsp&quot;,&quot;text&quot;:&quot;Weaver Time Lapse (Agh&#39;s Scepter)&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:1,&quot;rowIndex&quot;:9}},{&quot;key&quot;:&quot;fcigq&quot;,&quot;text&quot;:&quot;Tusk Snowball&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:0,&quot;rowIndex&quot;:10}},{&quot;key&quot;:&quot;aaauv&quot;,&quot;text&quot;:&quot;Oracle Fate&#39;s Edict&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:1,&quot;rowIndex&quot;:10}},{&quot;key&quot;:&quot;77vc0&quot;,&quot;text&quot;:&quot;Oracle Purifying Flames&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:0,&quot;rowIndex&quot;:11}},{&quot;key&quot;:&quot;1h73b&quot;,&quot;text&quot;:&quot;Terrorblade Sunder&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:1,&quot;rowIndex&quot;:11}},{&quot;key&quot;:&quot;13dfq&quot;,&quot;text&quot;:&quot;Outworld Destroyer Astral Imprisonment&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:0,&quot;rowIndex&quot;:12}},{&quot;key&quot;:&quot;fkj7f&quot;,&quot;text&quot;:&quot;Pugna Decrepify&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:1,&quot;rowIndex&quot;:12}},{&quot;key&quot;:&quot;1bhgn&quot;,&quot;text&quot;:&quot;Shadow Demon Disruption&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:0,&quot;rowIndex&quot;:13}},{&quot;key&quot;:&quot;b8tbm&quot;,&quot;text&quot;:&quot;Marci Rebound (Agh&#39;s Shard)&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:1,&quot;rowIndex&quot;:13}},{&quot;key&quot;:&quot;dbv1u&quot;,&quot;text&quot;:&quot;&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:0,&quot;rowIndex&quot;:14}},{&quot;key&quot;:&quot;12t72&quot;,&quot;text&quot;:&quot;Ethereal Blade&quot;,&quot;type&quot;:&quot;table-cell&quot;,&quot;inlineStyleRanges&quot;:[],&quot;entityRanges&quot;:[],&quot;data&quot;:{&quot;alignment&quot;:&quot;L&quot;,&quot;colCount&quot;:2,&quot;colIndex&quot;:1,&quot;rowIndex&quot;:14}}]}"><div class="" data-block="true" data-editor="d83866" data-offset-key="5sv89-0-0"><div data-offset-key="5sv89-0-0" class="public-DraftStyleDefault-block public-DraftStyleDefault-ltr"><span data-offset-key="5sv89-0-0"><span data-text="true">There is an inconsistency with which single-target friendly spells and items can or cannot get disabled by </span></span><span data-offset-key="5sv89-0-1" style="font-weight: bold;"><span data-text="true">turning off ally help</span></span><span data-offset-key="5sv89-0-2"><span data-text="true">.</span></span></div></div>
    

Can be disabled | Cannot be disabled
-- | --
Force Staff/Hurricane Pike | Wind Waker (Pierces BKB)
Bane Nightmare | Vengeful Spirit Nether Swap
Keeper of the Light Recall | Pudge Dismember (Agh's Shard)
Snapfire Gobble Up (Agh's Scepter) | Dark Seer Ion Shell
Snapfire Firesnap Cookie | Earth Spirit Enchant Remnant (Agh's Scepter)
Earth Spirit Boulder Smash | Earth Spirit Geomagnetic Grip (Talent)
Winter Wyvern Cold Embrace | Rubick Telekinesis (Agh's Shard)
Kunkka X Marks The Spot | Phoenix Supernova (Agh's Scepter)
IO Relocate | Weaver Time Lapse (Agh's Scepter)
Tusk Snowball | Oracle Fate's Edict
Oracle Purifying Flames | Terrorblade Sunder
Outworld Destroyer Astral Imprisonment | Pugna Decrepify
Shadow Demon Disruption | Marci Rebound (Agh's Shard)
  | Ethereal Blade

The spells listed above that cannot be disabled can be used by malicious players on the same team to grief teammates. And there's nothing that can really be done about it, since the disable ally toggle doesn't work for them.

</div>
</body>
</html>

**Comment by Digital47** [comment]
Did they fix tiny toss?

**Comment by Dillerfax** [comment]
> Did they fix tiny toss?

Tiny Toss is not single target, it grabs the unit closest to Tiny, if you could disable that by turning off ally help it would be abused as a advantage

**Comment by AbyssalD2** [comment]
Disabling help should also stop your allies from denying you or your creeps.

**Comment by Aluerie** [comment]
Why suggestion about denies is downvoted and called funny ?

Not so long ago as Enchantress I had a teammate following my big creep trying to deny it from half hp over the whole jungle, kinda annoying ; same can be said about obvious grief Doom-denies - annoying. 

I do not see how disabling such situations from happening is "1k mmr text". Where is downside ?

**Comment by Dillerfax** [comment]
> Why suggestion about denies is downvoted and called funny ?
> 
> Not so long ago as Enchantress I had a teammate following my big creep trying to deny it from half hp over the whole map, kinda annoying ; same can be said about obvious grief Doom-denies - annoying.
> 
> I do not see how disabling such situations from happening is "1k mmr text". Where is downside ?

Fair point
I already removed my dislike, i dont know why but i misinterpreted when he said "your creeps", i pictured lane enemy creeps in my head.

**Comment by NMOTH** [comment]
> > Why suggestion about denies is downvoted and called funny ?
> > Not so long ago as Enchantress I had a teammate following my big creep trying to deny it from half hp over the whole map, kinda annoying ; same can be said about obvious grief Doom-denies - annoying.
> > I do not see how disabling such situations from happening is "1k mmr text". Where is downside ?
> 
> Fair point I already removed my dislike, i dont know why but i misinterpreted when he said "your creeps", i pictured lane enemy creeps in my head.

I interpreted as lane creeps as well. as controlled and dominated units aren't exactly creeps. 
but it is still dumb even for controlled units and hero denies. Better your ally deny than enemy getting the last hit on them.

**Comment by Daar543** [comment]
It's about "disable help" in general, meaning all actions which have frequent drawbacks (ignoring niche things like giving you dmg buff -> you die because of blademail), so denies should also be included.

The best thing would be to put these into the "Settings" section and select which ones would stay enabled/disabled by "Disable help".

**Comment by jeffhill** [comment]
The list of abilities missing a disable help check will be fixed in the June 8th update.

I haven't disabled denies or Doom devours on creeps owned by allies with disable help on. It wouldn't be terribly difficult to do this technically, it's just a different feature from "fix the bug with these existing abilities" and would require some conversations with the gameplay folks (so it would take longer to fix than just "fix this bug"). If that feature is still useful (and it does sound useful to me) - please put in an issue just for that, so folks can vote on how important that feature is?

**Comment by masuie** [comment]
This article is unquestionably among the finest in the history of articles. I read fresh articles sometimes if I find them fascinating despite the fact that I am an old "Article" collector. And I think this one belongs in my collection since I found it to be rather intriguing. Excellent job! [nytimes wordle](https://nytimeswordle.io)
