### ISSUE TITLE
[Suggestion] Add game timer to on-hover tooltip on the post-game screen graphs

### ISSUE THREAD

**Issue by Readie** [jeffhill/Dota2#1506]
### Description

When viewing the post-game graphs there is some ambiguity to what time in-game the various segments actually represent - my request is to add the exact time to the tooltip like in this image mock-up: https://i.imgur.com/XviL7Nb.jpeg

**Comment by althaj** [comment]
Why exactly do you need to know the exact minute and second displayed on the graph?

**Comment by Readie** [comment]
> Why exactly do you need to know the exact minute and second displayed on the graph?

The exact second isn't strictly speaking necessary - but if the minutes are displayed then the seconds may as well be to not only provide additional clarity for users (If it just had the minutes number then some people would doubtless not understand their meaning), but also to provide just that little more additional information.

As for why I want the time at all - because at the moment I have no idea what actual meaning that graph has. First of all we have a pretty chunky vertical indicator - are the figures relevant to the start, the end, or the middle of that bar? Then the steps that you can move it in don't seem to map particularly neatly to the numbers at the bottom of the graph. On the example where I took the screenshot there are 10 steps between 0:00 and having the cursor over 10:00, but only 9 more until the cursor is over 20:00.

Finally, including the actual time allows players to also go into replays and find the events that correlate to notable changes on the graph significantly easier.
