### ISSUE TITLE
Sniper's top hat ambient effect is broken

### ISSUE THREAD

**Issue by SnabrielSnarsch** [jeffhill/Dota2#1552]
his tophat ambient effects is broken
![ambient effect](https://user-images.githubusercontent.com/106764413/175756557-7479e2dd-7f4e-4fd5-8baa-5508f3bfc5d4.png)

this is the fixed version ![Occultist%27s_Pursuit_Preview_1](https://user-images.githubusercontent.com/106764413/175756531-e6027640-da97-4cc1-ae12-9cc45eb8d9e1.png)

**Comment by Astiberon** [comment]
#798
Duplicate.
Close and vote for this please.
