### ISSUE TITLE
Clip Builder Not Working on Macbook

### ISSUE THREAD

**Issue by NadimKawwa** [jeffhill/Dota2#1577]
### Description

When Playing on a macbook and using clip builder, the result of the export is 1) a .wav file and 2) a series of .jpg images.
Ideally I would expect a mp4 file or some other video format.
See the screenshot below for example.

Machine used:
MacBook Pro (14-inch, 2021)
MacOS Montery Version 12.4

### Screenshots

[](url
![Screen Shot 2022-06-25 at 10 52 39 PM](https://user-images.githubusercontent.com/40652202/175801409-5bf704ff-edeb-4c62-b1a4-c50859d82e21.png)
)

**Comment by Soong45** [comment]
https://github.com/jeffhill/Dota2/issues/1225#issuecomment-1155240225
Expected behaviour, it's unfortunately just how it's implemented for Mac and Linux
