### ISSUE TITLE
Necro HeartStopper Aura + Level 20 Talent

### ISSUE THREAD

**Issue by shaileshgarg** [jeffhill/Dota2#1578]
### Ability name

Heartstopper Aura

### Description

Necro's level 20 Talent +32% Heartstopper Regen Reduction, is supposed to reduce the Health regen of enemies, but currently doesn't seem to be doing anything.

### Example Match ID (and possibly Timestamp)

-

**Comment by Bokoloony** [comment]
As far as I can tell it works normally, doing exactly what it says : it reduces the health regeneration of an enemy unit. It does not reduce heals, but it does work vs spells that provide HP regen (e.g. LC's Press the Attack).

You could argue it _should_ reduce heals as well, but that's out of the scope of this gthub I think.

**Comment by shaileshgarg** [comment]
Tried in Demo, equip level 30 LC with 6 hearts, HP regen is 197.2 before or after the Talent.
