### ISSUE TITLE
Shift queue move unable to path through units?

### ISSUE THREAD

**Issue by twelvebarsblue** [jeffhill/Dota2#1600]
### Description

If you use shift queue to move through a unit blocking your way, your unit will not attempt to circle around the blocked unit and instead just cancel out the queued command.

Example shown in video below

https://streamable.com/5fhdt8

**Comment by icegoddess222** [comment]
I cannot replicate this.

Are you sure you're not accidentally using Direction Move as well?

**Comment by twelvebarsblue** [comment]
After your comment I went and tested on my alt account, to my surprise it worked fine without issue (ie as expected). So I figured its something on my settings, I duplicated the exact settings and options from my alt account to my main but still no dice.

I am stumped. If anyone could point out what's causing this much appreciated.

**Comment by twelvebarsblue** [comment]
I made a video showing my settings

https://streamable.com/qr8yzg

Help appreciated.

**Comment by icegoddess222** [comment]
I think youre having an issue with Directional Move.

Rewatching your first video, you can see your Move Command indicator has both an Arrow pointing down and a Flag. The Arrow down indicates Directional Move and the Flag indicates a shift queued move order.

Try putting cl_dota_alt_unit_movetodirection 0 in your console and see if that fixes it. You can try cl_dota_alt_unit_movetodirection 1 as well. This command toggles whether or not you use Directional Move while holding ALT.

**Comment by twelvebarsblue** [comment]
> I think youre having an issue with Directional Move.
> 
> Rewatching your first video, you can see your Move Command indicator has both an Arrow pointing down and a Flag. The Arrow down indicates Directional Move and the Flag indicates a shift queued move order.
> 
> Try putting cl_dota_alt_unit_movetodirection 0 in your console and see if that fixes it. You can try cl_dota_alt_unit_movetodirection 1 as well. This command toggles whether or not you use Directional Move while holding ALT.

Tried both settings, no dice. I even reseted the hotkeys to no avail.

**Comment by Aphotic** [comment]
curious while having your shift key consoled to directional move will shift normal queued commands work normally?

**Comment by twelvebarsblue** [comment]
> curious while having your shift key consoled to directional move will shift normal queued commands work normally?

Hi yes it worked normally except for movement which was changed to directional move. Pretty nifty of valve engine and great if you are SF main (I remembered now, I was planning to master SF with that LOL).
