### ISSUE TITLE
Blink dagger

### ISSUE THREAD

**Issue by Krev5** [jeffhill/Dota2#162]
### Item name

Blink Dagger

### Description

If targeted outside of its natural range, it will blink for around 1000 units instead of its maximum 1200

### Example Match ID and Timestamp

.

**Comment by isRobertMa** [comment]
This is an intended mechanic, penalty Blink Distance: 960

**Comment by Krev5** [comment]
> 

Any officials that have actually said that it is intended?

**Comment by Uwila** [comment]
Not only is it an intended mechanic, it is also documented in the alt-text of the item:

"If you used Blink to teleport to a distance over the maximum range, you'll be teleported 4/5 of the maximum range instead."

As far as I'm concerned this issue should be closed, there's nothing to fix.

**Comment by NMOTH** [comment]
This is intended mechanic. Not a bug.
