### ISSUE TITLE
DUPLICATION BUG # 1311, PLEASE DEAL IT

### ISSUE THREAD

**Issue by dsltyyz** [jeffhill/Dota2#1620]
### Description

after client update 7.31d, can't stop speak when repeated enter key G to speak in the game!!!
util now, this bug always occurred

[#1311](https://github.com/jeffhill/Dota2/issues/1311)

### Example Match ID (and possibly Timestamp)

6615994463

### Screenshots

![BUG截图](https://user-images.githubusercontent.com/9079696/174079967-95835974-e789-4bfd-bdfa-b08503e21dd1.jpg)
![20220621203310_1](https://user-images.githubusercontent.com/9079696/174816056-4470921c-391b-44f9-84ef-6eec90cfd71b.jpg)

**Comment by althaj** [comment]
Stop intentionally creating duplicate issues.
