### ISSUE TITLE
Linken's Sphere blocking two spells/items?

### ISSUE THREAD

**Issue by Sch1nken** [jeffhill/Dota2#1626]
### Item name

Linken's Sphere

### Description

Linken's sphere blocking first one item and very shortly after a spell. The item (Orchid) does trigger Linken's but it does not go on cooldown, also there is no sound effect. Shortly after Grimstroke casts Phantom's Embrace and triggers Linken's again. This time the cooldown is triggered and the sound is audible.

Attacker: Grimstroke
Target: Queen of Pain

This happened in the span of 0.74 seconds. Sadly the Combat Log does not log Linken's?

For the provided match id:
First Linken's trigger (via Orchid): 59:02.36
Second Linken's trigger (via Phatom's Embrace): 59:03.10

This happened several times in the match (I thought I was going crazy for not being able to silence Queen of Pain....).

You can hear the two linkens triggers (and see the effect). 

Side by side video at 0.25x Speed:
https://user-images.githubusercontent.com/11414422/176236341-f9293eb7-b778-45b0-8645-7d161e5e8df3.mp4

### Example Match ID and Timestamp

6638819016 - 59:03

**Comment by icegoddess222** [comment]
Queen of Pain has a talent at 25 providing her Spell Block on a 18 second cooldown. 

The talent's effect should probably be given a different color to differentiate it though, honestly.
