### ISSUE TITLE
New Focus Fire Illusion Interaction is Inconsistent

### ISSUE THREAD

**Issue by ExplodedCow** [jeffhill/Dota2#1632]
### Ability name

Focus Fire

### Description

Last night's change:

> - Changed Focus Fire auto-target logic so that when illusions are spawned, the auto-target of focus fire is disabled. Attacking the focus fire target once again will restart the auto-target and fire while moving logic.

Isn't working correctly for some illusion effects.

- If Windranger uses Focus Fire on a Phantom Lancer, then the Lancer uses Doppelganger, Windranger auto-attacks a random Lancer - this seems like exactly the intended behaviour from the change.
- However, the same does not apply to Naga Siren's Mirror Image, Chaos Knight's Phantasm, Shadow Demon's Disruption, or Manta Style - Windranger always resumes attacking the real hero like she used to.
Oddly, if you combine multiple of these effects (EG - Manta Style, then Mirror Image), then it works as expected.

**Reproduction**
This can be tested easily enough in demo or a custom lobby.
- Spawn as Windranger, create an enemy Naga, give her Manta Style (and a couple of Hearts for good measure).
- Turn on free spells / WTF mode.
- Level Focus Fire on Windranger, cast it on Naga.
- Have Naga circle around Windranger casting _either_ Manta or Mirror Image.
_- Windranger continues attacking the real Naga, no matter where she is in the illusion formation._
- Have Naga use both Manta and then Mirror Image, or vice versa.
_- Windranger now 'forgets' the real Naga, as expected._

This was tested with auto-attack set to "Standard", in case that part is relevant.

### Example Match ID (and possibly Timestamp)

None

**Comment by zeroclona** [comment]
You better to close this and re-open #21 with this message

**Comment by Aluerie** [comment]
from [Jeffhill comment](https://github.com/jeffhill/Dota2/issues/21#issuecomment-1170319097) 

>Dropping aggro on the real hero during illusion creation is an unintended balance change and will be changed back to the previous behavior (similar to Razor's Static Link) in the hotfix later today.

So it was fixed yesterday. You can close this issue.

**Comment by ExplodedCow** [comment]
Tested and confirmed - closing.
