### ISSUE TITLE
When watching a friend live, selecting 'Player Perspective' does not always work.

### ISSUE THREAD

**Issue by Uwila** [jeffhill/Dota2#164]
### Description

It seems quite random but most of the time it does not work. You simply right-click a friend in your friend list who's playing and select the option to watch them live. In the panel where you can select the camera you select 'Player Perspective' and then click on the player whose perspective you want by clicking their hero at the top. In a replay this would now show you the game from their perspective, but when watching a friend live this often doesn't work. It does seem to work when watching with a delay though. (The default, non dota-plus option).

### Example Match ID (and possibly Timestamp)

N/A; it only malfunctions when watching live.

**Comment by guigax** [comment]
[Duplicate](https://github.com/jeffhill/Dota2/issues/5), @jeffhill response: "This should be fixed in the update we're planning to ship on June 8th"
