### ISSUE TITLE
Dota 2 cant run on 240hz on fullscreen with directx

### ISSUE THREAD

**Issue by icookiegg** [jeffhill/Dota2#1662]
### Description

You cannot run dota2 "fullscreen" at 240hz with directx11. (there is no option and enforcing with launch options do not work either). 240hz is only available with borderless.

![wwwwww](https://user-images.githubusercontent.com/108528702/176892135-478d713b-d9da-4efa-b24c-26ffd40f6173.png)
![wwwwwww](https://user-images.githubusercontent.com/108528702/176892173-0721066a-36c6-44b8-b4a5-d62eb5e7837a.png)

**Comment by TheZett** [comment]
Cant you use "Use my monitor’s current resolution" at the top to get 1080p @240hz?

**Comment by icookiegg** [comment]
> Cant you use "Use my monitor’s current resolution" at the top to get 1080p @240hz?

it automatically sets "borderless window" when used

**Comment by icookiegg** [comment]
activating virtual super resolution on amd control panel solved the issue
