### ISSUE TITLE
techies bug

### ISSUE THREAD

**Issue by art3mis1smz** [jeffhill/Dota2#183]
### Description

idk when happend but i think thats randomly when techies learn second ability (w) ,always a yellow flash is under techies and you dont know ,its anoying alot

### Example Match ID (and possibly Timestamp)

6590893341

**Comment by Uwila** [comment]
Cannot reproduce: I have watched the replay and also tried to reproduce this in the demo, but I don't see a permanent yellow flash when techies' second skill is learned.

**Comment by NMOTH** [comment]
Cannot reproduce on my device. 
Can you post screenshot of your in game settings and your PC specs

**Comment by art3mis1smz** [comment]
i think it had fixed this week ( i handt saw techies this week) sorry for waisting ur time about a buged it had been fixed 🙏

**Comment by Uwila** [comment]
All good, thank you for at least taking the time to close the issue and doing your part in keeping the issue tracker clean.
