### ISSUE TITLE
Bug that won't let me play

### ISSUE THREAD

**Issue by Chuchelllo** [jeffhill/Dota2#184]
### Description

This bug appeared in February with patch 7.31. It makes it very hard to play. It consists in the fact that Battle Pass has not yet been released, which is why I have no desire to play.

### Screenshots

![image](https://user-images.githubusercontent.com/106774505/171725031-938e679c-0a23-4d6c-989f-48233ecb835c.png)

**Comment by Uwila** [comment]
Sadly I don't have the power but honestly this should be an immediate ban. You are why we can't have nice things. Be a decent person and don't fill the issue tracker up with bullshit like this.

**Comment by isRobertMa** [comment]
classic redditors

**Comment by NMOTH** [comment]
**Please don't abuse this repo for  your reddit shit posting.
There are enough issues ( most which are people just now knowing how computers work or how in game mechanics work) and duplicates to go through already. Jeff is one person. You aren't contributing.**

**Comment by Chuchelllo** [comment]
You can delete it. I said what I wanted

**Comment by Uwila** [comment]
@Chuchelllo I don't know how many people manage this repo but if it's just JeffHill personally, I think it's a somewhat stupid remark to just say "You can delete it". At the moment of writing there's already 183 open issues; the least you can do is click the button to 'Close' this issue so other people don't have to deal with your trolling.

**Comment by urda** [comment]
This user purely joined GitHub, a professional software development site, to troll this bug report.

I recommend to all to head over to their user page at https://github.com/Chuchelllo and click "Block or Report" and go ahead and file a report.

<img width="329" alt="image" src="https://user-images.githubusercontent.com/1648492/171752559-6cd07d8e-f539-4292-9c28-7959cd250937.png">

@Chuchelllo this behavior might fly on your childish reddit, it is not tolerated here.

**Comment by urda** [comment]
> You can delete it. I said what I wanted

@jeffhill can we get this dude banned?

**Comment by NMOTH** [comment]
> This user purely joined GitHub, a professional software development site, to troll this bug report.
> 
> I recommend to all to head over to their user page at https://github.com/Chuchelllo and click "Block or Report" and go ahead and file a report.
> 
> <img alt="image" width="329" src="https://user-images.githubusercontent.com/1648492/171752559-6cd07d8e-f539-4292-9c28-7959cd250937.png">
> 
> @Chuchelllo this behavior might fly on your childish reddit, it is not tolerated here.

he is a troll and should be banned but not because he has new account.

 I have a decade old github account with projects and multiple open source contributions. But I made a new one specifically for this forum. To avoid doxing myself and avoid creeps stalking my online profiles. And I suggest you do the same.

**Comment by archindar5665** [comment]
### But I made a new one specifically for this forum. To avoid doxing myself and avoid creeps stalking my online profiles. And I suggest you do the same.

The rest of us only do this when trolling. Still those who cant not just do it on main accounts.

**Comment by Chuchelllo** [comment]
> You are why we can't have nice things.

I'mthe reason why DotA is still beta, but funny thing - Why do you think people joke about this topic? Do you think they're just joking that Valve doesn't care about the game? Just because there is no content and the game still has bugs that have been in the game since patch 7.00 and such thoughts appear.

**Comment by ronanharris09** [comment]
Reiterating my points from #324.

If you have the mental capacity to get this far, might as well go ahead and apply for a job at Valve to responsibly take the proper actions and guide this masterpiece we all love forward. You seemed to be quite well thought and expressive. Your stance in the community might seem to be very controversial yet you are able to demonstrate how much far ahead you are right now in leading the initiative to take the right steps to solve the issue we are all dealing with right now.

With all due respect, this is not a satire, nor a reddit copypasta, please tell us all of your thought in a constructive manner by opening up a new posts will all the changes that we can all discuss professionally. If you decide to keep things like this or even dox me instead, go ahead, turn it into your own benefit.

I will stand with the rest of the people here to contribute in a decent, and collective manner to look forward to your future issue to elaborate on the technical details you have not disclose so far despite the effort.

**Comment by maakep** [comment]
> You can delete it. I said what I wanted

No, you cannot delete, that requires GitHub support and that you accidentally included sensitive information and has a reason to delete.
