### ISSUE TITLE
Medusa's Split Shot is disabled by break

### ISSUE THREAD

**Issue by Uwila** [jeffhill/Dota2#185]
### Description

I'm not sure whether this is

a. A bug
b. Undocumented behavior

But it's one of the two. The problem is very simple: When Medusa is affected by break, for example from Silver Edge, she cannot use Split Shot. Other toggle-able attack modifiying abilities are not treated as passives (for example: Drow Ranger's Frost Arrows or Silencer's Glaives of Wisdom).

I suppose that Medusa's split shot was breakable when it was a passive (when it should be) and when changed to a toggle-able ability the effect of break was not removed. Perhaps it was an oversight and it should be fixed, or perhaps it was intended for balance reasons in which case it would be good to at least show this in the alt text.

### Example Match ID (and possibly Timestamp)

I don't have one handy but it's easily reproducable in demo.

**Comment by TheZett** [comment]
You are confusing Toggle spells with Active Attack Modifiers.

Active Attack Modifiers can be set to auto-cast, such as Drow’s Frost Arrows.
These ones do not care about Break, but are prevented by silences.


Meanwhile Toggle spells can only be turned on or off, such as Trolls Q or Phantom Lancer’s Phantom Rush.

Toggle spells stay enabled and fully functional even if you are silenced, but they cannot be toggled on or off while silenced.

Some Toggle spells are (partially) disabled by break, such as Troll’s root (the rest of Berserker’s Rage stays functional), while others are not disabled at all (Medusa’s Mana Shield).

**Comment by Uwila** [comment]
I guess that's my bad then. I would like it to be documented more clearly, but I guess I cannot say definitively that it is a bug.
