### ISSUE TITLE
[Ability Draft] Venge Aura + Unleash

### ISSUE THREAD

**Issue by RGBKnights** [jeffhill/Dota2#191]
### Description

When you combine Venge Aura illusion + Unleash gives infinite attacks while active.
Check out the Death Prophet in the match ID provided. After they die with Aghanim's Upgrade the Vengeful Spirit illusion have unlimited unleash procs.

### Example Match ID (and possibly Timestamp)

6600359204

**Comment by AmanovAkbar** [comment]
You really gotta elaborate on what you mean. I literally got nothing from what you wrote.

**Comment by RGBKnights** [comment]
Updated the description and added a match ID of the game that happened today.
