### ISSUE TITLE
[Ability Draft] Spirit Bear 

### ISSUE THREAD

**Issue by RGBKnights** [jeffhill/Dota2#196]
### Description

- Spirit bear does not die when the owner of the spirit bear dies, as it would in normal dota. 
- If the owner dies, Spirit bear can continue to attack while in a 1100 radius of the owner's corpse.

### Example Match ID (and possibly Timestamp)

0

**Comment by RGBKnights** [comment]
No its simple if you understand how to use Github at all.
https://github.com/jeffhill/Dota2/issues?q=is%3Aissue+is%3Aopen+Ability+Draft

**Comment by RGBKnights** [comment]
> Just consolidate all the issues in one post. You dont have to create multiple issues. It will be hard and confusing for the devs.

No its simple if you understand how to use Github at all.
https://github.com/jeffhill/Dota2/issues?q=is%3Aissue+is%3Aopen+Ability+Draft

**Comment by NMOTH** [comment]
PLEASE PROVIDE SCREEN RECORDING OR MATCH ID. You saying @Naaveen-Kumar doesn't understand how github works, but you are just spamming the issue page without providing ANY details, VISUALS or CONTEXT.

**Comment by RGBKnights** [comment]
Not everything has a match id and requiring one is just stupid. This has been verified and tested by the AD community use the [Console Commands ](https://dota2.fandom.com/wiki/Ability_Draft#Console_Commands) to setup and test a draft. 

Don't believe me TEST IT YOUR SELF! We even build a [tool ](https://lotus.highgroundvision.com/) to help in setup the console commands.

**Comment by Naaveen-Kumar** [comment]
> Those are separate issues, the only thing they have in common is game mode. You won't consolidate Turbo issues into single ticket, will you?

Just look at this one
https://github.com/jeffhill/Dota2/issues/182
This is what i meant when i said 'consolidate'. All the bugs are related to ability draft right? They are all happening when having a specific combination of spells right? Just create a list/table like 'spell combos - issue' format.

**Comment by x42bn6** [comment]
> > Those are separate issues, the only thing they have in common is game mode. You won't consolidate Turbo issues into single ticket, will you?
> 
> Just look at this one #182 This is what i meant when i said 'consolidate'. All the bugs are related to ability draft right? They are all happening when having a specific combination of spells right? Just create a list/table like 'spell combos - issue' format.

By that argument, you may as well consolidate most of the issues in this project into one issue "normal (non-Ability Draft) issues".

Personally, both your issue and this one are fine.  #182 is presumably something that a developer can pick up and fix in batches.  But Ability Draft bugs each likely need someone to go through each one, replicate them, debug them, etc.

Now, if there was an issue like "50% of heroes are missing Ability Draft-specific descriptions", then yes, one issue would work.
