### ISSUE TITLE
[Ability Draft] Tether + Essence Flux

### ISSUE THREAD

**Issue by RGBKnights** [jeffhill/Dota2#199]
### Description

Tether does not transfer mana gained from Essence Flux.
Setup video: https://vimeo.com/716986302

### Example Match ID (and possibly Timestamp)

N/A

**Comment by NMOTH** [comment]
PLEASE PROVIDE SCREEN RECORDING OR MATCH ID. Wiring a sentence without context or proof doesn't help anyone.

**Comment by RGBKnights** [comment]
Not everything has a match id and requiring one is just stupid. This has been verified and tested by the AD community use the [Console Commands ](https://dota2.fandom.com/wiki/Ability_Draft#Console_Commands) to setup and test a draft. 

Don't believe me TEST IT YOUR SELF! We even build a [tool ](https://lotus.highgroundvision.com/) to help in setup the console commands.

**Comment by AmanovAkbar** [comment]
> Not everything has a match id and requiring one is just stupid. This has been verified and tested by the AD community use the [Console Commands ](https://dota2.fandom.com/wiki/Ability_Draft#Console_Commands) to setup and test a draft.
> 
> Don't believe me TEST IT YOUR SELF! We even build a [tool ](https://lotus.highgroundvision.com/) to help in setup the console commands.

If you guys tested it and even have a tool, why not just provide a screen recording for the bug? That would be rather helpful.

**Comment by RGBKnights** [comment]
@NMOTH & @AmanovAkbar Most of these issues came of the list we where maintain for the AD community since Nov2021 its not like we have video of these lying around (other then the rare case). BUT thanks to said console commands we are able to reproduce its setup for all to see https://vimeo.com/716986302
