### ISSUE TITLE
You can get stuck inside Euls if phased.

### ISSUE THREAD

**Issue by KouroshShaban** [jeffhill/Dota2#20]
Game ID: 6598324040
Game time: 25:57

I was phased due to Shadow Walk as Bounty Hunter and got stuck inside my allied Ursa who was Eulsed by the enemy Mars. It actually caused me to die in this case, but the game was already won anyway.

**Comment by mdiller** [comment]
Ooo yeah this has happened to me more than a couple times. Video for posterity:

https://user-images.githubusercontent.com/3231343/171984222-409c52ad-4748-4644-86fc-75a1d28718d3.mp4

**Comment by jeffhill** [comment]
This will be fixed in the hotfix today. Thank you for the bug report!
