### ISSUE TITLE
Dota Plus Chat Wheel bug

### ISSUE THREAD

**Issue by Wondermarin** [jeffhill/Dota2#204]
### Description

Arcana's rarity items do not affect the voice chat wheel, the voice acting remains standard.
While the persona affects the voice acting.

**Comment by NMOTH** [comment]
this is duplicate of #93 , please close this

**Comment by prasedenica** [comment]
Thanks for this great topic. Hope you will contribute more to the forum
[duck life](https://ducklife.online)
