### ISSUE TITLE
Sandstorm on Low Graphics 

### ISSUE THREAD

**Issue by artilexx** [jeffhill/Dota2#222]
### Ability name

Sandstorm

### Description

Maybe not necessarily the result of a bug (idk so decided to post here anyway) but Sandstorm's radius is incredibly hard to make out in lower graphics settings. Shows up clearly when Effects Quality is set to High. The sandstorm visual effect you see is not accurate when graphics settings are on the lower-end, causing players with low-end PCs to suffer. Think adding a solid visual indicator/border would be sufficient if the effect is impossible to make work on low settings because its a particle :)

![High settings](https://user-images.githubusercontent.com/97213042/171738548-a2b112e9-d5a7-44c8-9e41-661cefff1dbd.jpg)
![Low Settings](https://user-images.githubusercontent.com/97213042/171738612-9668c0b6-888a-4c72-9e58-ee4aacd53847.jpg)

### Example Match ID (and possibly Timestamp)

not match specific

**Comment by jeffhill** [comment]
I've changed the low-quality sandstorm effect to also include the slightly more opaque "edge ring" element that's present in the high quality effect. You should now be able to judge the edge of the sandstorm equally well in high and low quality and the edge ring wasn't the expensive part of the effect anyhow.

This change will ship in the July 8th update. Thank you for the bug report!

**Comment by erikbeach1** [comment]
<a href="https://google.com/">google</a>

**Comment by erikbeach1** [comment]
That might be an effect error
<a href="https://scratchgames.io/">scratch games</a>
