### ISSUE TITLE
Elder Titan Earth Splitter Damage

### ISSUE THREAD

**Issue by jerezereh** [jeffhill/Dota2#233]
### Ability name

Earth Splitter

### Description

Elder Titan's Earth Splitter appears to have incorrect damage amounts with level 4 of his passive, Natural Order. The tooltip says it does 50% of maximum hp at level 3, but when calculating it in demo mode I came out to 56% at level 3. This damage boost seems to only happen when enemies are affected by a level 4 Natural Order; all other levels seem too come out to the correct damage total. 

I believe armor or magic reduction from level 4 Natural Order may be reducing the resistance below 0%, though both are displayed on the character details as 0%.

This is also visible from the health bar's of enemies hit: 
![image](https://user-images.githubusercontent.com/1996106/171742281-9d5f4de1-7308-4ec5-a656-d4b4df3de14b.png)

### Example Match ID (and possibly Timestamp)

None

**Comment by TheUnholyWrath** [comment]
For the combat log, seems like when they're the same damage value they don't get logged. If you have level 4 aura and have them only under the spirit it gives both damage values. If they have any magic resistance or armor you also get 2 values.

I can't replicate the first bug, Natural Order definitely isn't reducing it below 0%, you can test it out with set physical and magic damage in the combat log. What items did your hero have? Are you sure you didn't have any spell amp?

**Comment by jerezereh** [comment]
Trying to replicate it and you're right. I must have had a spell amp effect on accident. Thanks.

Issue closed.
