### ISSUE TITLE
Casting Press the Attack on yourself as Legion Commander when you have the AOE talent should cast it in an AOE around you.

### ISSUE THREAD

**Issue by aoisensi** [jeffhill/Dota2#24]
Copied by https://www.reddit.com/r/DotA2/comments/hyf42y/casting_press_the_attack_on_yourself_as_legion/

**Comment by natesampo** [comment]
https://user-images.githubusercontent.com/22483011/171687051-88af3e8b-cb3f-4e7b-b730-76e601fbf948.mov

This issue has already been fixed

**Comment by Peasant255** [comment]
it used to trigger me that LC turns around for self cast, but I think this is fixed now right? (it didnt happen when I tested in demo)

**Comment by ptcruisn** [comment]
> it used to trigger me that LC turns around for self cast, but I think this is fixed now right? (it didnt happen when I tested in demo)

It stills happens in demo mode for me. LC turns 180 degrees before casting, which is basically a false cast point. If this is intentional, can someone help me understand why? Also, when self-casting with free spells on, she casts it twice in a row with only one use of the ability. That part probably won't ever matter in a real game, but it certainly seems weird.

**Comment by Peasant255** [comment]
> > it used to trigger me that LC turns around for self cast, but I think this is fixed now right? (it didnt happen when I tested in demo)
> 
> It stills happens in demo mode for me. LC turns 180 degrees before casting, which is basically a false cast point. If this is intentional, can someone help me understand why? Also, when self-casting with free spells on, she casts it twice in a row with only one use of the ability. That part probably won't ever matter in a real game, but it certainly seems weird.

thats weird. I checked again both demo and lobby, it doesnt happen to me lol. you sure ur game is up to date?

**Comment by SnabrielSnarsch** [comment]
Same happens to dark seer with the aoe surge talent

**Comment by LokeLok** [comment]
This has been fixed btw, see #22. You can close this since it's resolved.
