### ISSUE TITLE
KOTL's Ultimate

### ISSUE THREAD

**Issue by arkhanov** [jeffhill/Dota2#243]
### Ability name

Spirit Form

### Description

Using Illuminate in Spirit Form causes the direction in which it is charging to be completely wrong. It would appear the blast is heading south but instead heads north east or something.
I'm attaching a match ID of some random KOTL, but I'm sure other people feel the same.

(I definitely didn't lose mid to a 22/0 KOTL)

### Example Match ID (and possibly Timestamp)

6597856943

**Comment by NMOTH** [comment]
> ### Ability name
> Spirit Form
> 
> ### Description
> Using Illuminate in Spirit Form causes the direction in which it is charging to be completely wrong. It would appear the blast is heading south but instead heads north east or something. I'm attaching a match ID of some random KOTL, but I'm sure other people feel the same.
> 
> (I definitely didn't lose mid to a 22/0 KOTL)
> 
> ### Example Match ID (and possibly Timestamp)
> 6597856943

please provide a screen recording or an actual match ID with time stamp, rather than a random game id. 
You writing 2 sentences without visuals doesn't help devs. Just makes the job harder.

**Comment by arkhanov** [comment]
> > ### Ability name
> > Spirit Form
> > ### Description
> > Using Illuminate in Spirit Form causes the direction in which it is charging to be completely wrong. It would appear the blast is heading south but instead heads north east or something. I'm attaching a match ID of some random KOTL, but I'm sure other people feel the same.
> > (I definitely didn't lose mid to a 22/0 KOTL)
> > ### Example Match ID (and possibly Timestamp)
> > 6597856943
> 
> please provide a screen recording or an actual match ID with time stamp, rather than a random game id. You writing 2 sentences without visuals doesn't help devs. Just makes the job harder.

Jeff closed it in another thread, thanks
