### ISSUE TITLE
I'm restricted from creating ANY custom games. Why?

### ISSUE THREAD

**Issue by rNtgg** [jeffhill/Dota2#25]
Hello, I need help.
I'm still restricted from creating custom game lobbies.

I mean, I can create, but my lobby is a ghost, does not show to anyone, so yea, same as nothing. Not a specific game, ANY custom game is restricted, so is not an issue with the game, is Dota/my account. Please help me solve this. If I have a punishment, maybe tell me when it ends?!
![steam-1](https://user-images.githubusercontent.com/106766180/171683908-a4a3a592-da95-4a08-990d-1a0f73da1c00.jpg)
![steam-2](https://user-images.githubusercontent.com/106766180/171683919-f6ed1c9a-10df-408d-8966-bd58bdb79bf3.jpg)

My profile: https://steamcommunity.com/id/rNt_gg/

Thanks a lot!

**Comment by Gromil** [comment]
there was some info about the bot check. Do you usually play normal dota games, or you only play custom games? If its latter then try playing several normal dota matches

**Comment by rNtgg** [comment]
I do only play custom games, ya. Turbo counts to "normal dota matches"?

**Comment by chrisinajar** [comment]
i exclusively play dota mods and my lobbies recently stopped appearing in the list, too.

**Comment by rNtgg** [comment]
Exactly that. No warning, no reports from others. I play silent. But lobby doesn't show. I can play normal, but creating is better to me so I can get my server.

**Comment by chrisinajar** [comment]
I also play with a private stack in discord, so I know I've never been reported. I'm also the author of the gamemode in question so it feels particularly silly.

**Comment by wersonit** [comment]
There was a post on reddit about silent bans if you haven't played any classic gamemodes, like All Pick for a long time.

**Comment by x42bn6** [comment]
If you exclusively play Arcade lobbies, as a workaround, a Valve developer suggested that the solution is to play - *and complete* - one game of normal matchmaking (Turbo also works).

https://reddit.com/r/DotA2/comments/unk743/valve_is_shadowbanning_suspected_bots_from/

According to the Atomic War developers, New Player Mode should also work.  Not sure about co-op (vs. bots).

(The best solution would be, of course, better bot detection in Arcade lobbies)

**Comment by rNtgg** [comment]
Thanks for the reddit post linked. Not a great solution by Valev devs, as my account from 2011 is now ~SUSPICIOUS~. I'll try to play some turbo games and test it. Ty.

**Comment by wersonit** [comment]
> Thanks for the reddit post linked. Not a great solution by Valev devs, as my account from 2011 is now ~SUSPICIOUS~. I'll try to play some turbo games and test it. Ty.
I guess it's not a problem for these people to buy old accounts and make bots out of them
