### ISSUE TITLE
Never-dying lifestealer

### ISSUE THREAD

**Issue by WasBooking** [jeffhill/Dota2#252]
### Ability name

Open wounds

### Description

Lifestealer presses open wounds on the enemy and presses the blade mail and he becomes immortal, he can survive Wraith King's Aghanim`s ult.

video: https://www.youtube.com/watch?v=_85MD_D6224

### Example Match ID (and possibly Timestamp)

video

**Comment by ahi-el** [comment]
Wow, what's the reason for this??

**Comment by Dopwop** [comment]
Tested and replicated, can confirm. 

Here is the combat log of Lion killing Lifestealer under Delay:
![Lifestealer-1](https://user-images.githubusercontent.com/106779797/172028798-5b43eded-e287-417c-bbaa-8d0faf994113.png)

https://old.reddit.com/r/DotA2/comments/uydabj/3_bugs_and_2_tips_in_731c/ (see #482)
A quote from @TheZett on reddit:
> The (...) issue is due to Open Wounds’s custom coded spell lifesteal being able to spell lifesteal off of HP Removal damage instances, unlike all other sources of spell lifesteal.
> It also lets you survive the guaranteed death of Wraith Delay (WK Aghs aura), if the guy who put you down is affected by Open Wounds.
> Open Wounds should not be able to spell lifesteal off of HP Removal damage instances, just like regular spell lifesteal behaves.

**Comment by shubhrathi** [comment]
This issue is included in #290

**Comment by jeffhill** [comment]
This will be fixed in the next hotfix. Thanks for the bug report!

**Comment by bifrurcated** [comment]
This feature with lifestealer has been working since [2017](https://youtu.be/dYWb4OKyxqo?t=161), although in matchmaking it did not help to win.
