### ISSUE TITLE
Search  issues when an EU server picked.

### ISSUE THREAD

**Issue by h4rdmol** [jeffhill/Dota2#275]
**Steps to reproduce:**
1. Click the Play Dota button
2. Select region Europe West or Europe East.
3. Press the find match button.
4. Observe. 
**Issue**: 3-5 players from Russia on the server. 
**Expected**: Russians are able to play only on RU server. All EU players suffering from playing with RU people.

**Comment by NMOTH** [comment]
This is not a bug.
