### ISSUE TITLE
The wraith hero's arcane element turns the first ability black when cast on an enemy and loses the arcane element effect.

### ISSUE THREAD

**Issue by ehome07** [jeffhill/Dota2#286]
### Cosmetic Item Name

ADVIENTO FANTASMA

### Description

The wraith with its arcana item throws a black dagger when you aim at the enemy. and does not have the arcana effect. the EFFECT turns black, I've been talking about it for a long time but until now nobody does anything to fix the effects of the first ability of said hero equipped with his arcane item. Please. the first ability is completely black when targeting an enemy

### Example Match ID

S/N

### Screenshots

![ARCANA FIRST ABILITY BUGG](https://user-images.githubusercontent.com/106786541/171763380-d550936e-449b-46cd-b651-79ad77cdce8b.png)

**Comment by JMekker** [comment]
I've been a spectre main since the arcana released and I've never had this issue before.

**Comment by NMOTH** [comment]
I have spec arcana, I can't replicate this in demo. Likely issue with your graphic settings.

**Comment by ehome07** [comment]
Yes, it is a graphic effect problem. in my pc, thanks you
