### ISSUE TITLE
Fantasy Roles are not correct for Team Secret Players Nisha and Crystallis

### ISSUE THREAD

**Issue by 5Starkiller3** [jeffhill/Dota2#295]
### Description

Currenly fantasy card of Nisha has the role of carry and fantasy card of Crystallis has the role of mid. It is possible that this bug happened because Crystallis replaced Sumail who was mid but actually Nisha switched back to mid and Crystallis will play carry (it is implied in the team secret announcement that crystallis will play carry).
In the screenshots you can see that Crystallis is in the pool with other mid players and Nisha is in the pool with other position 1 and 3 playes.

### Screenshots

![secret2](https://user-images.githubusercontent.com/8082443/171767769-cc6fba6a-596c-4592-9c86-1227d522e8cc.jpg)

![secret1](https://user-images.githubusercontent.com/8082443/171767772-799a44c8-9389-4601-9a35-976d8a9e10eb.jpg)

**Comment by wersonit** [comment]
There's also an issue with stand-ins. 
When Ceb replaced Misha in OG roster, Misha card didn't give any points, and we didn't have Ceb card instead.

**Comment by 5Starkiller3** [comment]
> There's also an issue with stand-ins. When Ceb replaced Misha in OG roster on the recent Major, Misha card didn't give any points, and we didn't have Ceb card instead.

That is also a big problem for fantasy. It can be tricky in some cases as the role of the new player might change depending on the day so it would require constant adjustments.

**Comment by 5Starkiller3** [comment]
It seems like this got fixed. Thanks!
