### ISSUE TITLE
Bloodseeker Thirst bug

### ISSUE THREAD

**Issue by ajtarasievic** [jeffhill/Dota2#308]
### Ability name

Thirst

### Description

If an ally kills enemy thirst heals for full (25%) instead of half (12.5%) value.
![Screenshot 2022-06-03 052207](https://user-images.githubusercontent.com/106774763/171774321-d405ad04-cd93-4eba-9f4e-11e31063a768.png)

### Example Match ID (and possibly Timestamp)

6569705664 - 04:23 (thirst lvl 2 here)

**Comment by Glitch9001** [comment]
it's intended 
![ICANT](https://user-images.githubusercontent.com/106767944/171786777-97799af7-9780-4ec0-96f0-d8c3225b3424.PNG)
