### ISSUE TITLE
Lone Drude bear items doesn't show up (post match)

### ISSUE THREAD

**Issue by fazo3131** [jeffhill/Dota2#317]
### Description

I don't know if this is a bug but we should be able to see the Bear items.

**Comment by NMOTH** [comment]
Can you post screenshot of them not showing up?

**Comment by fazo3131** [comment]
Sadly I'm not able to at the moment but you can go to any match where you played with or against a lone drude and confirm it

**Comment by arkhanov** [comment]
> Can you post screenshot of them not showing up?

Just checked a LD game that got done 5 minutes back, was able to see bear's items post match.
![Capture](https://user-images.githubusercontent.com/106779898/171849386-997e9159-682a-4808-876d-bb34165ba663.PNG)

**Comment by fazo3131** [comment]
Thank you for the screenshot they seem to have fixed it, from when i played LD
