### ISSUE TITLE
Hoodwink Sharpshooter can't change direction

### ISSUE THREAD

**Issue by Nujaka** [jeffhill/Dota2#32]
When casting Sharpshoother, you cannot change its direction or release it if you, after casting it, try to use any skill or items in any direction that is not directly in front of Hoodwink.

Hoodwink can't turn to face the direction of the follow up skill/item, and must face the direction Sharpshooter is aimed at. It ends up getting stuck and you can't turn in ay direction, but if you issue a cancel/stop command, it cancels the item/skill and you can aim/release the ultimate again.

I mentioned that in reddit a few days ago but didn't get much attention. [Here is an example video.](https://youtu.be/ZxRb4Gbe6YQ)

**Comment by sfee7a** [comment]
true, this should be the case only if u Shift queue the abilities, but in normal circumstances, casting an ability out side of ur range (or direction in this case) should be overwritten automatically with the next spell/order

**Comment by jeffhill** [comment]
This will be fixed in the next hotfix, likely on Monday.

**Comment by LokeLok** [comment]
@jeffhill Did this fix ship into the game? I just tested it and it's not working.

https://user-images.githubusercontent.com/106764092/175325893-69731037-b782-459c-8c84-f41288cb89b9.mp4

**Comment by Nujaka** [comment]
@LokeLok I've also tested it, it still has the same behaviour and the issue persists.
But seems to work when you try to cast something out of range and then cast it within range.
I'm not able record a video right now but might do it later today.

**Comment by Nujaka** [comment]
@LokeLok What I mentioned is casting the spell out of range and then casting it in range, all this while Sharpshooter is charging. I think I was mistaken as I couldn't reproduce it the way I thought, and instead found a [different behaviour](https://youtu.be/M5F3z_j069U).

**Comment by jeffhill** [comment]
Dang it - this behaves different between the development build and the shipping build for some reason. I can't repro the problem in the development build, but the shipping build still has a bug. Digging into it.... thank you for the comments!

**Comment by jeffhill** [comment]
Ok, hotfix shipped with the code from the dev branch. Can you give it another go in a lobby?

**Comment by LokeLok** [comment]
Now it works, thank you, Jeff!

**Comment by Mishka-VFX** [comment]
Now for some reason when Hoodwink starts channeling he doesn't show the line indicator which helps you aim the spell but is able to turn even if he uses spells. On the other hand, Rubick's Sharpshooter does have a line indicator but he is unable to cast or change direction if he tries to use his spells in the opposite direction of the Sharpshooter ( he can't even cast End Sharpshooter)

https://user-images.githubusercontent.com/96825320/175775077-4b6db8f7-9f09-4a9f-986f-db9dcd26a2f4.mp4

**Comment by LokeLok** [comment]
Hoodwink's line is there, it does't show if you cast it as an enemy Hoodwink(so no bug here). But yes, Rubick is suffering from the same bug as Hoodwink, with stolen Sharpshooter.

**Comment by Mishka-VFX** [comment]
Oh, my bad. Line is indeed there XD

**Comment by jeffhill** [comment]
The bug here is with Hoodwink or Rubick using a unit target ability while aiming (rather than a point target). This will be fixed in the next hotfix.
The issue with the target line is limited to Hero Demo; it only shows for the owner of the hero casting the Sharpshooter. Since spawning enemies in Hero Demo gives you control of them, but you're not technically the owner, you don't see the effect. As it appears to work correctly in-game, I'm just going to leave that as-is.

**Comment by Mishka-VFX** [comment]
I have one more question about this Jeff: Both Rubick and Hoodwing are now able to cast their spells while channeling Sharpshooter but only in the direction of the Sharpshooters line. Using spells in any other direction will just buffer them and cast after the Sharpshooter is finished. Is this how it's supposed to work?
