### ISSUE TITLE
I cannot inflict damage or select the Drow with arcane.

### ISSUE THREAD

**Issue by Isolamento322** [jeffhill/Dota2#323]
### Cosmetic Item Name

Drow´s Arcane

### Description

In any game that confronts the Drow with her arcane, it is impossible for me to hit her or select a power against her. An error appears in her image in the game itself, in the loading screen or even in the player's profile. I must emphasize that it is only with the arcane, because in the training room or in a game without the arcane is normal like any other hero; also it only happens to me because other players are not affected by this problem. I wish they could fix the bug in my account, I got tired of banning that hero in every game. 

### Example Match ID

6598698457

### Screenshots

https://user-images.githubusercontent.com/106795944/171789893-c2d01c35-16ce-4b45-8b96-bf80133a8544.mp4

https://user-images.githubusercontent.com/106795944/171789987-f996138d-03e8-4883-8d58-e2c78b720c2a.mp4

**Comment by ptcruisn** [comment]
That is definitely weird. Have you tried verifying your game files through Steam?

**Comment by NMOTH** [comment]
> That is definitely weird. Have you tried verifying your game files through Steam?

To add to this if you don't know how to verify, right click on your game on the sidebar in steam library, and select properties. then click this
![image](https://user-images.githubusercontent.com/106769588/171916972-d258754c-3916-49ec-be82-c04b1f3d44c3.png)

**Comment by Isolamento322** [comment]
thank you very much
