### ISSUE TITLE
Some Neutrals dont have HotKey on their skill while I Use Legacy Key

### ISSUE THREAD

**Issue by weiseng101** [jeffhill/Dota2#327]
Neutrals that dont have Hotkey while people use **Legacy Key** :

- WARPINE RAIDER
- ANCIENT ICE SHAMAN
- FELL SPIRIT
- HARPY SCOUT
- OGRE BRUISER
- HILL TROLL
- WILDWING

Kindly check & fix it, your help will be appreciated. 

Thanks yah~~ 

![nc2](https://user-images.githubusercontent.com/15317730/171794682-aa1ecd51-7b1a-478c-9cf7-fdfc86f49c75.jpg)
![nc1](https://user-images.githubusercontent.com/15317730/171794688-5d949009-fc62-45f2-bb89-d9e1acacf247.jpg)
![nc3](https://user-images.githubusercontent.com/15317730/171794689-1b1b3230-3938-4345-8ddf-fb6a398d659d.jpg)
.

**Comment by anonymo0se** [comment]
related issue
#7

**Comment by MrMooEar** [comment]
ok these were fixed in the above issue, but I also added the Ice Shaman. Nice catch!

**Comment by Jacklaw12** [comment]
Thanks for sharing. It's so interesting.
