### ISSUE TITLE
[Ability Bug] Self Casting AOE buff talents, while moving, causes hero to turn before casting [Legion Commander] [Dark Seer]

### ISSUE THREAD

**Issue by howardtaylor** [jeffhill/Dota2#334]
### Ability name

Press the Attack; Surge

### Description

Issue: Legion Commander and Dark Seer both have talents which turn their single-target-buff-spells into an AOE. When attempting to self cast these skills while moving (i.e. double tapping key), the hero will turn before casting the spell.

https://user-images.githubusercontent.com/19278554/171795338-87fd44b4-6374-4463-9996-f05766146b4b.mp4

https://user-images.githubusercontent.com/19278554/171795320-838df16d-ba6c-4c8e-ba12-7201b8dcf76f.mp4

Expected behavior: When self cast, the hero stops and casts the spell in the direction they are currently facing. For example, the behavior seen when Warlock's single-target-buff-spell Shadow Word is upgraded to an AOE using his Aghanim's Shard.

https://user-images.githubusercontent.com/19278554/171796585-c4955827-e247-4080-a115-cd29353fd84e.mp4

To recreate bug: 

1. Skill AOE talent
2. Enter a move command
3. Double tap skill

### Example Match ID (and possibly Timestamp)

See attached videos

**Comment by OMEGALULW** [comment]
Talents don't belong in the game so this is fixed simply by removing talents.
