### ISSUE TITLE
Summer is on. Where is summer treasure from dota plus?

### ISSUE THREAD

**Issue by Yan00r** [jeffhill/Dota2#335]
### Description

Summer is on. Where is summer treasure from dota plus? It's 3rd June. Spring is over. Where is compendium? Where is summer treasure?

### Screenshots

![image](https://user-images.githubusercontent.com/106772815/171797721-174cc748-8af1-42e8-869b-0c2590062dc0.png)

**Comment by Yan00r** [comment]
Valve time i know, but why so long?

**Comment by anonymo0se** [comment]
https://www.dota2.com/newsentry/3190249489765271734
![image](https://user-images.githubusercontent.com/53087065/171797996-3c4ad854-bd88-420e-98a7-b775e64cd513.png)

Also, not a bug.

**Comment by Yan00r** [comment]
thanks

**Comment by anonymo0se** [comment]
> thanks, i did not read this news
Now that you've read it, please close the issue.

**Comment by Yan00r** [comment]
how?

**Comment by Aluerie** [comment]
![image](https://user-images.githubusercontent.com/33165440/171799449-c0801751-2a22-4fd2-87a0-227df36e237d.png)

**Comment by Yan00r** [comment]
thx
