### ISSUE TITLE
Zeus Heavenly Jump Stuck

### ISSUE THREAD

**Issue by pzdeoduco** [jeffhill/Dota2#342]
### Ability name

Heavenly Jump 3rd skill

### Description

Zeus heavenly jump stuck in a forest terrain at the bottom of the map.

https://user-images.githubusercontent.com/34449031/171804622-f5a6b6ed-94c7-4eca-9c59-9a0589bc2932.mp4

![download (1)](https://user-images.githubusercontent.com/34449031/171805298-e5213ae6-e6e0-493f-b8c5-f8450d1c8c70.png)

 

### Example Match ID (and possibly Timestamp)

6595702272

**Comment by BlueHammer** [comment]
While annoying this is not a bug at all, that's how the spell works.

**Comment by pzdeoduco** [comment]
Ouch. I can go to that terrain but can't get out? That's odd.

**Comment by NMOTH** [comment]
This is not a bug please close this. Thanks

**Comment by pzdeoduco** [comment]
I "accidentally" jump over that terrain now I can't get out just because "that's how the ability works" lol funny spell.
