### ISSUE TITLE
Axe Legs

### ISSUE THREAD

**Issue by taranbyxti** [jeffhill/Dota2#351]
### Cosmetic Item Name

Fists of Axe unleashed & Days of the demon - misc 

### Description

The bug is the intersection of the legs of these accessories.

### Example Match ID

No

### Screenshots

![image](https://user-images.githubusercontent.com/106804828/171816973-c1f84729-18ca-4cb6-9247-565dde49aa11.png)

**Comment by CYAXARES-76** [comment]
Not a bug since the Days of the Demon misc was meant to work on the default Axe model.

**Comment by NMOTH** [comment]
This is not a bug. visually unpleasant sure, model clipping is common, but not a game impacting bug. Please close this.
