### ISSUE TITLE
[Ability Draft] Shards

### ISSUE THREAD

**Issue by RGBKnights** [jeffhill/Dota2#36]
- Skywrath's shard does not not grant Shield of the Scion.
- Shadow Demon's shard does not not grant Demonic Cleanse.
- Tinker's shard does not not grant Warp Flare.
- Zeus's Static Field

**Comment by Tiarin-Hino** [comment]
Zeus Shard is also missing.

**Comment by FieryFirefly** [comment]
I thought Shield of the Scion works it just doesn't have an ability icon

**Comment by RGBKnights** [comment]
Zeus's Static Field seem to be missed in the list but I will close this issue and open a new open for past patch info.
