### ISSUE TITLE
Bounty Hunter's Immortal bug

### ISSUE THREAD

**Issue by CYAXARES-76** [jeffhill/Dota2#371]
### Cosmetic Item Name

Tines of Tybara

### Description

Tines of Tybara: Having a weird clipping in the claw

### Example Match ID

6573121134

### Screenshots

![BH](https://user-images.githubusercontent.com/106813672/171844523-b4c3a93a-ae53-4037-aedd-6be3ecb7df23.jpg)

**Comment by NMOTH** [comment]
This is not a bug. minor cosmetic clipping is not game impacting bug. Please close this.
