### ISSUE TITLE
Sven's Immortal Bug

### ISSUE THREAD

**Issue by CYAXARES-76** [jeffhill/Dota2#375]
### Cosmetic Item Name

Vigil Signet

### Description

Vigil Signet was missing in Sven's Hero Portrait. 

### Example Match ID

No

### Screenshots

![Uploading Sven.jpg…]()

**Comment by CYAXARES-76** [comment]
![Sven](https://user-images.githubusercontent.com/106813672/171846689-bc77e30f-8897-4db1-98a3-b101990db8f2.jpg)

**Comment by SnabrielSnarsch** [comment]
i think this is intentional, otherwise it will block most of the portrait

**Comment by CYAXARES-76** [comment]
> i think this is intentional, otherwise it will block most of the portrait

![image](https://user-images.githubusercontent.com/106813672/171885117-2dddbebd-8907-4362-828f-659105256915.png)
It doesn't block that much

**Comment by NMOTH** [comment]
This is intentional, not a bug.
Please close this. thanks
