### ISSUE TITLE
Vaccum affecting Storm Spirit mid zap

### ISSUE THREAD

**Issue by Jeanjitre** [jeffhill/Dota2#39]
Dark seer vaccum is cancelling storm zap if cast on his path even if storm's supposed to be unvulnerable during zap.

Game id with 2 instances: 6590922024 (don't have the time stamp unfortunately)

**Comment by WingDota** [comment]
In 7.23 they changed Vacuum to "affect invulnerable units" so this may be intended

**Comment by Jeanjitre** [comment]
Missed that :o 

Thank you
