### ISSUE TITLE
Implement bug report into Dota client

### ISSUE THREAD

**Issue by maxkuzn** [jeffhill/Dota2#409]
### Description

It's not a bug report, but rather a suggestion. Implement bug report function in Dota2 client.
For example, it would be much easier both for players and developers, if players could record a bug. For example, a button after a game, or event reproduce it record by a game in demo mode that have changed a lot recently.

**Comment by NMOTH** [comment]
Except, as you can see even on this repo, most of the reports are people just not understanding how computers work, or how game mechanics work. Do you want all the low mmr people just mass fill the bug report just cause they dont understand game mechanics?

Please kindly close this ticket.
