### ISSUE TITLE
Axe's cosmetic armor is floating

### ISSUE THREAD

**Issue by sadaharu25** [jeffhill/Dota2#414]
### Cosmetic Item Name

Pauldrons of the Warboss and Fists of Axe Unleashed

### Description

Axe's Pauldrons of the Warboss armor is floating when partnered with Fists of Axe Unleashed

### Example Match ID

no id. cosmetic bug

### Screenshots

https://user-images.githubusercontent.com/68681493/171881761-56c92dab-0713-46df-b691-49c7d8369a7c.mp4

**Comment by jeffhill** [comment]
The animation team has fixed this one, and it'll ship in the hotfix today. Thank you for the bug report!
