### ISSUE TITLE
Tidehunter is always turned on his back in treasures

### ISSUE THREAD

**Issue by SnabrielSnarsch** [jeffhill/Dota2#415]
### Cosmetic Item Name

Treasures Chests in general

### Description

it's been like that since his last immortal item was released, not sure if that's intentional

### Example Match ID

none

### Screenshots

![tide hunter back](https://user-images.githubusercontent.com/106764413/171884182-69e43534-8ec8-4709-a1e1-bc721589819b.png)

**Comment by jeffhill** [comment]
The animation team has fixed this, and the fix will ship in the June 8th update. Thank you for the bug report!
