### ISSUE TITLE
Weather Effects "Weather Spring" has not functioned as it did six years ago for about three years, maybe more 

### ISSUE THREAD

**Issue by Frosttek** [jeffhill/Dota2#429]
### Cosmetic Item Name

Weather Spring

### Description

The effect of falling leaves; leaves on the ground, in the water; tree foliage; flowers. ITS ALL GONE. This item only changes the lighting on map now, nothing more. 

### Example Match ID

It happens in every match 

### Screenshots

This is what it looked like six years ago https://youtu.be/_OjNO9U7k-I?t=153 and what it looks like now https://youtu.be/sAiPH9rKxM0?t=95. Please fix it T_T

**Comment by NMOTH** [comment]
Possibly related #31

**Comment by carlx-s** [comment]
I hope they fix it, it's my favorite :(

**Comment by jeffhill** [comment]
This will be fixed in the hotfix later today.
