### ISSUE TITLE
pudge shard

### ISSUE THREAD

**Issue by art3mis1smz** [jeffhill/Dota2#434]
### Ability name

dismember

### Description

when pudge gonna cast dismember on teammate (with shard) disember sound will play for enemy team (pudge's enemy)

### Example Match ID (and possibly Timestamp)

6600085691 30-44

**Comment by Memoframe** [comment]
Dismember sound in general is audible even thru the fog, it's intended.

**Comment by art3mis1smz** [comment]
> Dismember sound in general is audible even thru the fog, it's intended.

spells with cast on teammats dont have to be general but something like night stalker ulti that global or luna ulti (better example i can tell you life stealer's ulti, just u can hear sound when he is in your vision but you can hear disemember sound on global when you cant see pudge)

**Comment by Memoframe** [comment]
Maybe it "should not" be like this but at this point it's intended and is not a bug.
This tracker is for bugs not for "i think you should change this to that" :D
![image](https://user-images.githubusercontent.com/15750345/172021889-308eae00-4081-4326-a19b-49e94b55824f.png)

**Comment by art3mis1smz** [comment]
at this point im agree thats not issue too
