### ISSUE TITLE
Incorrect position of the profile level in the trophies page

### ISSUE THREAD

**Issue by abhijitsaxena** [jeffhill/Dota2#436]
### Description

As you can see in the attached screenshot the profile level has a misplaced positioning. The screen resolution is 1920x1080 and borderless window.

Also, the battle pass trophy level might need some bottom padding.

A low priority, cosmetic bug. :)

### Screenshots

![image](https://user-images.githubusercontent.com/20242852/171921597-f31682e0-c452-4da1-9081-3959fb8b864f.png)

**Comment by NMOTH** [comment]
This is a duplicate of #331, mind closing it?

**Comment by abhijitsaxena** [comment]
> This is a duplicate of #331, mind closing it?
My bad, didn't go through the previous ones. Closed now, thanks.
