### ISSUE TITLE
MK Wukong Command does not work with MK desolator or other desolators in team

### ISSUE THREAD

**Issue by Arturbbe** [jeffhill/Dota2#440]
### Item name

Desolator

### Description

When casting Wukong Command with MK with desolator, debuff does not apply to enemy if statues hit enemy first.

Message says [Armor reduced by 0].
While the [Armor redueced by 0] debuff is active, any heroes with desolator will not have the -6 armor debuff applied, it will keep refreshing the timer on the [reduced by 0]

If other teammates have desolator, debuff will not apply either.

Once [Armor reduced by 0] message disappears, any new attacks from MK or teammate will apply correct -6 armor debuff.

I'm not sure about the intended interaction:
![2022-06-03 19-32-46_Moment](https://user-images.githubusercontent.com/106835612/171926507-d20d79ba-ba39-47d8-a3c5-e03bcd685bad.jpg)

- If desolator does not work with MK ulti, at least the hero one should work
- If it should work... well it doesn't right now.

### Example Match ID and Timestamp

Demo mode

**Comment by MrDemonRush** [comment]
Just a visual bug, if you check the damage values with and without debuff, damage would be higher with it

**Comment by TheZett** [comment]
This is just a visual bug.
The bug appears because the source of the debuff is the MK clone, which are always considered to be invulnerable and hidden (banished).
If the source of a debuff is invlunerable and banished, the tooltips may default to zero (also shows a blank icon).

Functionally the debuffs are working fine, you can test this yourself by utilising the dummy target in demo mode.

**Comment by Arturbbe** [comment]
Hi Thanks yes I saw the numbers match, just visual.

**Comment by KoziLord** [comment]
While the actual damage numbers may be correct, they still do not display properly and in my opinion the issue should stay open.

**Comment by Arturbbe** [comment]
I can re-open this or create new issue as "incorrect tooltip" which it actually is.
