### ISSUE TITLE
d+ guide on bloodseeker dont work

### ISSUE THREAD

**Issue by lonkalsim** [jeffhill/Dota2#444]
### Description

if you try pick dota+ assistant on hero bloodseeker the only thing you will see is an endless loading

### Screenshots

![image](https://user-images.githubusercontent.com/104431158/171938471-cb19dfd0-a11e-4e1f-a2a8-9a52bb513454.png)

**Comment by Talexsmith** [comment]
dota plus guides dont work in demo

**Comment by fazo3131** [comment]
Hope you close that case, your in Demo hero how will D+ analyze what items to get?
