### ISSUE TITLE
Dota+ quests

### ISSUE THREAD

**Issue by lonkalsim** [jeffhill/Dota2#452]
### Description

all quests associated with the dpc app cannot be completed

### Screenshots

![image](https://user-images.githubusercontent.com/104431158/171940313-5b28860f-0538-4000-b613-52af4e92e1d7.png)

**Comment by iamquoz** [comment]
Dublicate of #142?

**Comment by NMOTH** [comment]
#142 duplicate please close

**Comment by lonkalsim** [comment]
> #142 duplicate please close

in that post, IOS is meant, and the quests is not performed even with android devices
