### ISSUE TITLE
Error in the description of Ancient Apparition's "Chilling Touch"

### ISSUE THREAD

**Issue by Doter121** [jeffhill/Dota2#474]
### Hero and spell

Ancient Apparition - Chilling Touch

### Description

Description of ability "Chilling Touch" hasn't got a line about damage type. Numbers of damage aren't painted in blue color.

### Screenshots

![ChillingTouch](https://user-images.githubusercontent.com/106838550/171957577-5b704be7-783a-47e4-8035-d1eac1889e0a.png)

**Comment by wersonit** [comment]
I think it would be better if you combined all these description issues into one
