### ISSUE TITLE
Error in the description of Techies' "Reactive Tazer"

### ISSUE THREAD

**Issue by Doter121** [jeffhill/Dota2#479]
### Hero and spell

Techies - Reactive Tazer

### Description

Description of ability "Reactive Tazer" has got a line about damage type without Aghanim's Scepter.

### Screenshots

![ReactiveTazer](https://user-images.githubusercontent.com/106838550/171958837-bb9ca999-b943-458c-9812-4d1cdcf718b6.png)

**Comment by NMOTH** [comment]
Hey do you mind combining all your error in description issues? Or link them all under a primary post?
These are all same issues just different heroes.  You can put each hero in separate comments under the same post.
