### ISSUE TITLE
Rubick's Telekinesis does nothing to heroes in Duel

### ISSUE THREAD

**Issue by TrueThaumaturge** [jeffhill/Dota2#480]
### Ability name

Telekinesis, Duel

### Description

Attempting to lift an enemy hero (or allied hero with agh's shard) while they are currently dueled will do absolutely nothing - no lift, no landing - but will put the spell on cooldown. I think this is unintentional behaviour because ideally telekinesis should do something on a duelled target. I've been flamed many times for not stunning during a duel when I literally can not.

Very easy to replicate in a test lobby or practice mode: get LC to duel a dummy and try using telekinesis on them.

### Example Match ID (and possibly Timestamp)

Very easy to replicate, don't have MID rn

**Comment by Usera2** [comment]
It seems its an intended mechanic.
[https://github.com/jeffhill/Dota2/issues/190#issuecomment-1145287029](url)

**Comment by NMOTH** [comment]
This is intended mechanic, it is literally in the wiki
![image](https://user-images.githubusercontent.com/106769588/171960000-950ca85a-ec01-4965-9838-3ffc2b97ddc6.png)
https://dota2.fandom.com/wiki/Legion_Commander

**Comment by TrueThaumaturge** [comment]
My bad, didn't realize an issue was already made and that this mechanic is intentional. It's a strange interaction but not a bug so I've closed it.

**Comment by jere535** [comment]
> This is intended mechanic, it is literally in the wiki ![image](https://user-images.githubusercontent.com/106769588/171960000-950ca85a-ec01-4965-9838-3ffc2b97ddc6.png) https://dota2.fandom.com/wiki/Legion_Commander

I must say that it clearly states that units cannot be moved, so the stun from telekinesis should still apply, but it doesn't.

**Comment by Cynaeon** [comment]
> This is intended mechanic, it is literally in the wiki ![image](https://user-images.githubusercontent.com/106769588/171960000-950ca85a-ec01-4965-9838-3ffc2b97ddc6.png) https://dota2.fandom.com/wiki/Legion_Commander

The wiki just tells how the skill currently works in the game, that doesn't mean it is intended, the wiki is not maintained by the developers. So that can't really be used as source like this.
