### ISSUE TITLE
Quality of Life: Please include turbo records in stat page and stone counts

### ISSUE THREAD

**Issue by Usera2** [jeffhill/Dota2#491]
### Description

For example hero's win and lose count and stats for inscribed gems.
In the past 2-3 years i only have played turbo games, but since turbo stats doesn't get recorded, the heroes play counts or stats like  first blood or rampage have not been changed in this time.
It doesn't matter if there is a second set of records for them, but still it would be nice to be recorded in the profile.

**Comment by mosi3883** [comment]
this place is for bug report not for suggestion, please close this topic
