### ISSUE TITLE
Spectator view locking on mid lane

### ISSUE THREAD

**Issue by tmr621** [jeffhill/Dota2#5]
Description: When loading into a game as a spectator, the camera view is locked into the mid t1 tower when the player you're watching is in the offlane.

Recreation:
1) Have friend playing in offlane or support in ranked roles. They're playing on dire side. 
2) Use watch friend live feature in Dota+ to view friend's game.
3) Game loads.

Expected result: game loads in with the player view as selected friend, with camera mirroring their movements and camera.  
Actual result: Game loads in with correct player selected, but camera is locked to Dire mid T1 tower. When selecting a different hero, issue occurs for players "right" (in team order) of the mid laner, but does not occur for the others. 

Issue resolves when offlane player dies, then respawns.

**Comment by jeffhill** [comment]
This should be fixed in the update we're planning to ship on June 8th. The code that fixes this is mixed in with other changes, so it's a little trickier than usual to just "hotfix." If it's still broken for you after the update, could you submit a new bug?

**Comment by tmr621** [comment]
Will do! Thanks!

**Comment by sgodwincs** [comment]
This seems to still be a problem.
