### ISSUE TITLE
Dark Willow Shadow Realm ignores Hoodwink Bushwhack

### ISSUE THREAD

**Issue by Wiolarz** [jeffhill/Dota2#501]
### Ability name

Shadow Realm

### Description

While Dark Willow Shadow Realm ignores Hoodwink Bushwhack.
It can be replicated in demo hero.

### Example Match ID (and possibly Timestamp)

6443404550

**Comment by anko** [comment]
Bushwhack doesn't hit invisible heroes either, nor other intangibility effects like Shadow Dance or Book of Shadows. Since it's consistent, I would imagine it's intentional? Would be nice if the tooltip mentioned it though (#394).
