### ISSUE TITLE
Enter a short summary here!

### ISSUE THREAD

**Issue by malicethegod** [jeffhill/Dota2#502]
### Hero and spell

DOOM first spell

### Description

the description does not indicate how much armor the first skill gives ( sry my eng bad )

### Screenshots

![image](https://user-images.githubusercontent.com/106849292/171968747-6dad900a-28d3-4dfc-a0bb-bfa347763a4f.png)

**Comment by isRobertMa** [comment]
Close this please, [duplicate](https://github.com/jeffhill/Dota2/issues/152)
