### ISSUE TITLE
Tier 5 item Apex +75 Primary Stat

### ISSUE THREAD

**Issue by SonodaHanami** [jeffhill/Dota2#523]
### Item name

Apex

### Description

We can find the previous change in patch note 7.30c
> Primary Stat Bonus reduced from 75 to 70

and no more later, but now it does +75 primary stat
which is right, 75 or 70?

### Example Match ID and Timestamp

6380457725

**Comment by johnsonloh6185** [comment]
Upvote for this

**Comment by cameron-valve** [comment]
This change was missed in 7.30c, the tooltip was accurate at +75, but this has been corrected to +70 and will go live later today.
