### ISSUE TITLE
[Ability Draft] Coaching with Dota+

### ISSUE THREAD

**Issue by RGBKnights** [jeffhill/Dota2#55]
If you are coaching a party, in the draft screen there will be a box of text (dota+ related) that blocks sight of the radiant 5th player's draft for the duration of the draft.

**Comment by Tiarin-Hino** [comment]
It's easy to reproduce and is always reproducible. You just need to coach party. I've never coached party of less than 5 people so not sure if this is affecting.

Steps to reproduce:
1) Coach party of 5 people
2) Search for Ability Draft game
3) Check Radiant lowest player in the draft screen.

Expected Results:
Player abilities are visible

Actual Results:
Player Results are hidden behind "enemies and allies" screen.

**Comment by Bloppppppp** [comment]
![Bugged ad coaching](https://user-images.githubusercontent.com/106782193/172050839-72c427d0-4a2a-40e5-a116-6b3d07458d66.JPG)

Screenshot --> Cant see 5th radiant abilities because it is blocked by the dota plus window
