### ISSUE TITLE
[Spell steal/Ability draft] Tether and Infest interaction

### ISSUE THREAD

**Issue by zeroclona** [jeffhill/Dota2#578]
### Ability name

Spell steal, Tether, Infest

### Description

This is a rare unintended broken feature. 
Infest can be used without breaking tether. It provides crazy sustain.
It works in ability draft and rubick can use it in all classic game modes.

YT link: https://youtu.be/eL0pBzBl7sk
I think its a bug cause this feature was fixed for IO + LS combo a long time ago (LS with aghs scepter could eat a Wisp tethered to him)

### Example Match ID (and possibly Timestamp)

Have no example match ID, sorry

**Comment by Bloppppppp** [comment]
https://github.com/jeffhill/Dota2/issues/263

This has already been raised - see comments at that thread

**Comment by zeroclona** [comment]
I have overlooked the thread while trying to find it, sorry
