### ISSUE TITLE
Monkey King hero does not apply on-hit debuffs if target is hit by clone first

### ISSUE THREAD

**Issue by baijiu57** [jeffhill/Dota2#582]
### Ability name

Wukong's Command

### Description

The Monkey King hero and clones share debuffs applied on hit using e.g. deso or orb of corrosion. Clones apply a zero-valued debuff (e.g. desolator reduced armor by 0) when attacking the enemy target. When the MK hero hits the target, it refreshes the zero-valued debuff rather than applying the appropriate value (e.g. -6 armor). The hero therefore cannot apply on-hit debuffs until the clone debuff runs out.

If the MK hero hits the target first, the effect is flipped -- attacks from clones refresh the duration of the non-zero-valued debuff.

In the Match ID linked, the Combat Log shows:
[25.39.62] "Tiny received Desolator debuff from Monkey King." This was applied by a clone and the Desolator debuff reads "Desolator attacks reduced your armor by 0." 
[25.45.08] "Monkey King hits Tiny for XX damage." This is an autoattack from the hero, after which Tiny still has debuff "Desolator attacks reduced your armor by 0" with a refreshed duration. Tiny's armor remains unchanged at 0+29.

This was reproduced in Demo.

### Example Match ID (and possibly Timestamp)

6599113854 - 25:39

**Comment by Daar543** [comment]
I wonder why do they even apply the zero-value debuff. Shouldn't they be clones as close to the original hero as possible, without breaking balance?

**Comment by MrDemonRush** [comment]
This issue has already been raised before and closed, here: #440

**Comment by baijiu57** [comment]
Thanks. I searched "Monkey" but not "MK" looking for previous reports. The damage numbers check out -- it's just a tooltip bug. Closing this.
