### ISSUE TITLE
[Ability Draft] Players Shuffling

### ISSUE THREAD

**Issue by RGBKnights** [jeffhill/Dota2#59]
Players not shuffled in the draft. 
The change in the [Nov 15th AD](https://www.reddit.com/r/Abilitydraft/comments/quv8qv/ad_patch/) Patch that added shuffling in lobbies broke party queue (for pubs) and you now always draft in party order.

**Comment by ZzZombo** [comment]
I oppose adding this back. This only serves to seed confusion as to the draft order later.
