### ISSUE TITLE
Beast Masters hawk dive bomb triggers linkens in Void Spirits Dissimilate

### ISSUE THREAD

**Issue by DarkEyeDragon** [jeffhill/Dota2#598]
### Ability name

Dive Bomb

### Description

When Beastmaster triggers dive bomb on Void Spirit and void spirit goes into dissimilate before it hits it will still trigger linkens sphere.

I don't have the match ID but i confirmed this in demo mode after i saw the video

### Example Match ID (and possibly Timestamp)

https://www.youtube.com/watch?v=9sfxZCrL0bE

**Comment by Dopwop** [comment]
#447

**Comment by DarkEyeDragon** [comment]
Closing as duplicate of #447
