### ISSUE TITLE
Tempest Double is able to copy Roshan Aghs/Shard consumable items

### ISSUE THREAD

**Issue by TheZett** [jeffhill/Dota2#60]
The Tempest Double is currently able to copy the consumable versions of Aghanims Scepter & Aghanims Shard that Roshan drops.

This allows it to consume the items itself without requiring the main Arc Warden to consume them.

It effectively allows you to copy the items with the Tempest Double and consume them, while the main Arc Warden can decide not to consume them and give them to his allies instead.

The Tempest Double should not be able to copy the "Aghanims Scepter - Roshan" and "Aghanims Shard - Roshan" items, but it should of course copy the buffs off of the main Arc Warden, if he has consumed these items himself.

**Comment by MrMooEar** [comment]
Nice catch! Marked those items as not tempest cloneable. Will go out with the next large update. 👍
