### ISSUE TITLE
Dota+ hero relics can't be seen by the account owner in his profile without activated Dota+

### ISSUE THREAD

**Issue by MrDemonRush** [jeffhill/Dota2#603]
### Description

See title. 

You can however see those in other profiles even if they don't have Dota+. As far as I know, this is a bug that persisted ever since D+ was introduced.

### Example Match ID (and possibly Timestamp)

Not applicable

### Screenshots

![image](https://user-images.githubusercontent.com/43213936/172052589-de98d909-bbe7-4e43-a3e9-e028cdd70077.png)
![image](https://user-images.githubusercontent.com/43213936/172053105-332344ed-5db1-4763-8ff5-dcd894a4d8af.png)

Friend account
![image](https://user-images.githubusercontent.com/43213936/172053944-1999e123-6c13-4170-9f48-59a5ff049476.png)

**Comment by Fi-eMan** [comment]
I think that is normal

**Comment by MrDemonRush** [comment]
> I think that is normal

I don't think so, no. If it was the other way around, with you being able to see your relics without D+ but others not seeing them it would make sense, but as it is currently it makes none.

**Comment by MrDemonRush** [comment]
> This is intended

There isn't any way in which the current implementation looks logical, so unless there is an official statement, you can't really say this is intentional.

**Comment by MrDemonRush** [comment]
> > > This is intended
> > 
> > 
> > There isn't any way in which the current implementation looks logical, so unless there is an official statement, you can't really say this is intentional.
> 
> It literally is in the dota + subscription description. You cant update or see relics unless you have active subscription.

DId you even read the text? My point was, why can't you see your relics without d+ but at the same time other people looking at your profile while also lacking d+ can? This makes no sense, which is the entire reason why I bothered with all the text. 

This is inconsistent with behaviour of levels, for example, which aren't shown in profile without activated d+, but you can still see your levels at heroes tab. This is also inconsistent with the ability to see your unlocked shards and their levels in d+ shop.

**Comment by Manuel-ReyGallard** [comment]
I agree it's inconsistent.

No D+ can see any relic but your own. Either remove option to see relics all together or allow you to see your own when subscription ends.

**Comment by MrDemonRush** [comment]
Patch brought relic changes, closed
