### ISSUE TITLE
Dota shop - search bug

### ISSUE THREAD

**Issue by hektor36** [jeffhill/Dota2#609]
### Description

typing "ac" for assault cuirass does not bring up assault cuirass like it used to, need to type assault

**Comment by geras256** [comment]
I just type "ass" now.

Anyway, this should be fixed, you are right.

**Comment by pontuslaestadius** [comment]
Was this shadow-fixed in 7.31d? AC is now a searchable term to bring up the item.

**Comment by opomuc** [comment]
@hektor36 can you please check if the issue persists on 7.31d? if not, you can safely close the issue :)

**Comment by hektor36** [comment]
fixed ty
