### ISSUE TITLE
Please allow us to report player in the next game after we commend them in the previous. 

### ISSUE THREAD

**Issue by Krev5** [jeffhill/Dota2#620]
### Description

Lets imagine. Game #1. A player is playing very well and not being toxic at all and he gets commended.
(Currently if we match in next game with the same player, they cannot be reported and or avoided).
Game #2. We get into a match with the same player, and now he was toxic whole game without any significant reason as well as broke his items. Now I want to give a  COMMUNICATION ABUSE report to that player and avoid him, but sadly its not possible, because there is not commend/report button above the player, since I commended him in the last game.

**Comment by real-vaLor** [comment]
Agree, on the topic of suggestions I think there should be the ability to commend/report if you disconnect as the game ends (i.e. as the ancient's breaking), I've had games where I've done this after particularly bad games and it sucks that you cant avoid them, or on the flip side commend your team if the game went well and you wished to. It is also very common people leave in this way so it should be considered.

In addition, I find it really strange you cant report someone for comms abuse after the game. I cant speak for anyone but the last thing im thinking about during a game is submitting a report on a toxic player, I always would think about/do it afterwards, but you only have the option to report cheaters, feeders, and boosters iirc.

**Comment by Yan00r** [comment]
You always can reboot dota and chek last match you've played and avoid player. So that's not a problem at all. If you don't want to get in this situation you can avoid player before you commented him.
