### ISSUE TITLE
Rubick stealing illuminate from kotl while kotl is in spirit form gives "spirit form" version of illuminate to rubick

### ISSUE THREAD

**Issue by MiioKyllinen** [jeffhill/Dota2#628]
### Ability name

Spell steal / illuminate

### Description

If kotl is in spirit form and casts illuminate and rubick is able to steal it, rubick will get the spirit form version of illuminate (meaning he summons a spirit to cast it for him).

It shouldnt work like this because rubick personally isnt in spirit form, for example he doesnt heal with this "spirit form" version of illuminate.

![image](https://user-images.githubusercontent.com/69619453/172091296-b4056be7-9f60-44d3-84cc-81f3fff86fbf.png)

Here you can see a rubick casting a separate illuminate without being in spirit form. Rubick shouldnt be able to do this unless he himself is in spirit form

### Example Match ID (and possibly Timestamp)

6603710241 at 13:38 rubick uses a stolen illuminate that originates from a spirit formed kotl (steal happened in 12:20)

**Comment by althaj** [comment]
This works as intended. Spirit form Illuminate is a different spell.
