### ISSUE TITLE
Dire secret shop range

### ISSUE THREAD

**Issue by Yoho11** [jeffhill/Dota2#64]
The dire secret shop has a very strange range behavior when approaching it from the highground (the area with trees to juke). There's an area near it where it's not usable even tho farther away you can use it. 
2 screenshots attached with examples.
In the first one you can see that I can use the shop
while in the second one even if I'm close I can't use the shop, this makes it very annoying during the game
![secretOK](https://user-images.githubusercontent.com/43831058/171688335-5c2f9a61-85f0-4645-8169-256d34878fab.png)
![secretNotOk](https://user-images.githubusercontent.com/43831058/171688350-906b5066-a820-4472-90bd-05a88aafac8c.png)

**Comment by jeffhill** [comment]
I've adjusted the trigger volumes around the secret shop to fix this. It's technically a map change, so to avoid making really big "hotfix" update downloads, this fix will ship with the June 8th update.

Thanks for the bug report!

**Comment by DxAxxxTyriel** [comment]
https://clips.twitch.tv/BillowingResourcefulCroissantPMSTwin-fQ4YMExirDuAKZbF 

Any idea why this happened ? @jeffhill

**Comment by Aphotic** [comment]
> [clips.twitch.tv/BillowingResourcefulCroissantPMSTwin-fQ4YMExirDuAKZbF](https://clips.twitch.tv/BillowingResourcefulCroissantPMSTwin-fQ4YMExirDuAKZbF)
> 
> Any idea why this happened ? @jeffhill

i think its better for you to create a new ticket for it,
most likely will not look up on closed/solved issues here

**Comment by DxAxxxTyriel** [comment]
> 

Seems to be the same issue honestly, but at least I showed the clip

**Comment by bobb-valve** [comment]
> https://clips.twitch.tv/BillowingResourcefulCroissantPMSTwin-fQ4YMExirDuAKZbF
> 
> Any idea why this happened ? @jeffhill

This is a different bug than here or #203. The search results are dismissing right clicks if the player doesn't have enough gold for the entire item. In this clip Gorgc has enough gold for the Vitality Booster but not an entire Vanguard.

The fix should go live in the next hotfix.

Thank you for the clip. It was helpful in figuring out the repro case.
