### ISSUE TITLE
Powershot does not always destroy Sprout trees from within

### ISSUE THREAD

**Issue by TheZett** [jeffhill/Dota2#65]
Powershot only destroys Sprout trees from within, if you walk around within the Sprout area prior to using Powershot.

If you stand still, get sprouted and then attempt to destroy the trees with Powershot, you will simply shoot through them, without destroying any sprout trees.

**Comment by somethingxful49** [comment]
Confirmed in demo mode and in a hosted lobby

**Comment by Aluerie** [comment]
Might be related. 

If you get sprouted, don't move and then use Euls on yourself - your hero will be pushed out from the trees: https://youtu.be/nw9LN-czJ_o

**Comment by mdiller** [comment]
Very interesting bug. Video recorded of this behavior below for posterity:

https://user-images.githubusercontent.com/3231343/171983559-86ac0549-072a-481c-b04b-0d38da53fd5a.mp4

**Comment by jeffhill** [comment]
This will be fixed in the next hotfix. Thank you for the bug report!
