### ISSUE TITLE
QOL - Queueing Power Treads should use the item that matches your hero's attribute.

### ISSUE THREAD

**Issue by eNelz** [jeffhill/Dota2#658]
### Description

Currently, queueing Power Treads sets you up to buy Boots of Speed, Gloves of Haste, and Belt of Strength. However, the item can be built with Band of Elvenskin or Robe of the Magi instead of Belt of Strength. If I want to purchase a Band of Elvenskin toward my Power Treads as my first item in the laning phase, I have to manually queue all three components of the item. It would greatly increase quality of life if queueing Power Treads would set you up to purchase the item that matches the primary attribute of your hero (e.g. Belt of Strength on a Chaos Knight, Band of Elvenskin on a Drow Ranger, Robe of the Magi on an Enchantress).

**Comment by somethingxful49** [comment]
I can confirm, the item currently assumes always to place a Belt of Strength in your quick buy, regardless if you have Band of Elvenskin in inventory.

**Comment by LiamWinterton** [comment]
I think for newer players this might be confusing. Learning all the item recipes is a pain for new players to begin with, having an item's recipe change between heroes would only make this harder and more confusing.

If anything, it's actually weird that there IS multiple recipes but it's not stated in the shop at all, you just have to know.

Could be worth having it so when you click treads in the shop you have:

| Items |     |                 |
|-------|-----|-----------------|
| Boots |     | Gloves of Haste |
| Str   | Agi | Int             |

Where the bottom row locks out when you purchase one, with a small tooltip explaining why.

**Comment by Aluerie** [comment]
Update: They actually changed it to work like this in 7.31d

**Comment by eNelz** [comment]
I'm not sure if this was because of this post or not, but it does seem to work like this in 7.31d. Thank you so much, Jeff and team!! This was the one QOL change I was really hoping for :')
