### ISSUE TITLE
Infinite redirect loop when browsing to non existing patch site 

### ISSUE THREAD

**Issue by glaserL** [jeffhill/Dota2#685]
### Description

When you browse to `https://dota2.com/patches/<NON_EXISTANT_PATCH>` you encounter a weird redirect loop. (Safari + Firefox)

### Example Match ID (and possibly Timestamp)

N/A

### Screenshots

https://user-images.githubusercontent.com/33624744/172419743-70060442-ece2-47c3-9231-22f6e5ee0746.mov

**Comment by AmanovAkbar** [comment]
Probably you should close the issue. Sounds unrelated.
