### ISSUE TITLE
Bramble Maze timings (edit: Please, close this report Jeff)

### ISSUE THREAD

**Issue by 777bronzestar** [jeffhill/Dota2#694]
### Hero and spell

Dark Willow - Bramble Maze

### Description

During the use of this ability, bushes capture enemies at different timings after disclosure, namely counterclockwise. 
(Because of this, I have to throw bushes with a different approach depending on the location).
But the bushes from Cursed Crown (Aghanim's Shard) grab at the same time - everything is correct here.

### Screenshots

(Sorry for the Cyrillic alphabet)
1 screenshot - The essence of the problem is in timings.
2 screenshot - Visual demonstration of the capture delay in timings.
3 screenshot - Bushes from Cursed Crown (Aghanim's Shard).
![1](https://user-images.githubusercontent.com/106770009/172458111-905dffac-7c52-4be6-be2e-c7b9a8547c7a.jpg)
![2](https://user-images.githubusercontent.com/106770009/172458123-d2340452-e992-40b5-b733-1caac47e43b4.jpg)
![3](https://user-images.githubusercontent.com/106770009/172458134-b73fc6f3-e80e-4096-b511-56a82d956da5.jpg)

**Comment by Bu3nyy** [comment]
This is intended. The brambles spawn in 0.075 second intervals, starting at the east bramble of the inner circle, going counter-clockwise (so, east, south, west, north, then the outer circle, north-east, south-east, south-west, north-west).

Also note that each bramble has an activation delay of 0.1 seconds after spawning, which is also intended.

You can read more about this in the [Dota 2 Wiki](https://dota2.fandom.com/ru/wiki/Dark_Willow)

**Comment by 777bronzestar** [comment]
> This is intended. The brambles spawn in 0.075 second intervals, starting at the east bramble of the inner circle, going counter-clockwise (so, east, south, west, north, then the outer circle, north-east, south-east, south-west, north-west).
> 
> Also note that each bramble has an activation delay of 0.1 seconds after spawning, which is also intended.
> 
> You can read more about this in the [Dota 2 Wiki](https://dota2.fandom.com/ru/wiki/Dark_Willow)

This is my mistake, and I admit it.
Although I have played about 2000 games on it, but I do not use the dota wiki, and I think that such details could be in the game itself. (It seems that the developers have chosen a way to attract newcomers to our game.)

**Comment by jeffhill** [comment]
@777bronzestar  Can you not close this yourself? I'm happy to close it for you if you'd like - just making sure the tracker isn't broken somehow.

**Comment by 777bronzestar** [comment]
@jeffhill I'm sorry to ask you to do this. But I looked all over the interface of this page, but I can not find this function to close this.
