### ISSUE TITLE
Some legacy keys need fix

### ISSUE THREAD

**Issue by avivon15** [jeffhill/Dota2#7]
Oracle aghs  'Rain of Destiny' have no hotkey assigned at all when using legacy keys.

Bloodseeker aghs 'Blood Mist' legacy hotkey is 'L' 
, Shadow demon shard 'Demonic Cleanse' legacy hotkey is 'L' 
, Dazzle aghs  'Good Juju' legacy hotkey is 'J' 
, Shadow fiend 'Necromastery' shard legacy hotkey is 'N'
and Weaver 'Geminate Attack' legacy hotkey is 'K'

 all have bad and odd hotkey location assigned too far right on the keyboard.

**Comment by CIO61** [comment]
Also, turning legacy keys into an importable hotkey preset instead of the current unmodifiable form would be much more useful, as in you always have the option to load the original legacy key set, but you can create your own hotkey set derived from it.

**Comment by Chairraider** [comment]
Suggestions and changes for legacy keys:

Fell spirit - Vex - V
Hill Troll - Ensnare - E
Wildwing - Tornado - T
Warpine Raider - Seed Shot - E
Ogre bruiser - Smash - E
Harpy Scout - Take Off - E
Giant Wolf - Intimidate - T

SD - demonic cleanse - use F instead of L
Dazzle - good juju aghanims upgrade - use F instead of J (which is almost as bad of a hotkey as L)
Oracle - rain of destiny - D
Bloodseeker - Blood Mist - use D instead of L
Weaver - Geminate Attack - use E instead of K
Shadow fiend - Necromastery - use E instead of N

**Comment by avivon15** [comment]
> Suggestions and changes for legacy keys:
> 
> Fell spirit - Vex - V Hill Troll - Ensnare - E Wildwing - Tornado - T Warpine Raider - Seed Shot - E Ogre bruiser - Smash - E Harpy Scout - Take Off - E Giant Wolf - Intimidate - T
> 
> SD - demonic cleanse - use F instead of L Dazzle - good juju aghanims upgrade - use F instead of J (which is almost as bad of a hotkey as L) Oracle - rain of destiny - D Bloodseeker - Blood Mist - use D instead of L Weaver - Geminate Attack - use E instead of K Shadow fiend - Necromastery - use E instead of N

all good just Bloodseeker use the hotkey 'D' for his 'Bloodrage'  so it also can be 'F'

**Comment by MrMooEar** [comment]
ok this should be fixed when the june update ships!
I changed the keys to your suggestions and added all of the missing neutral creeps.

**Comment by LokeLok** [comment]
For future reference when it comes to legacy keys, i think the devs should not assign any hero hotkeys beyond the letter "Y" "G" and "B". Mostly is an issue when an old spell get an active component.

**Comment by OMEGALULW** [comment]
You can't have legacy keys for things that didn't exist in WC3 DotA since legacy keys literally refer to the hotkeys in DotA...

**Comment by moveaxebx** [comment]
Valve leaves me no choice but to write an injection dll that will change hotkeys at runtime.
