### ISSUE TITLE
[Ability Draft] Mortimer Kisses Aghs upgrades suddenly become unusable

### ISSUE THREAD

**Issue by Dagsss** [jeffhill/Dota2#713]
### Description

Match ID: 6606850896 
Issue: Our Terrorblade who drafted Metamorphosis, Mortimer Kisses, Tricks of the Trade, and Feral Impulse suddenly lost his Gobble Up and Spit Out abilities. At 21:27 of the game (and earlier than that), he can still use the Gobble Up and Spit Out abilities. At 22:10, the 2 abilities suddenly blacked out and became unusable. He tried dropping the aghs and disconnecting then reconnecting but the abilities are still unusable.
![20220608112334_1](https://user-images.githubusercontent.com/106859871/172525242-0e0b6b88-47a5-471e-9fd8-71b57dbddf88.jpg)
![20220608112128_1](https://user-images.githubusercontent.com/106859871/172525261-502449a7-be6f-4dae-bb39-47535494d5eb.jpg)

### Example Match ID (and possibly Timestamp)

6606850896 - 21:27, 22:10

**Comment by Dagsss** [comment]
> Related to #33

Should i close this?

**Comment by CodyCenters** [comment]
This happens with several other abilities where Aghs scepter/shard grants an additional ability.

I've had it happen with Death Pulse and its granted ability Deathseeker in match: matchid=6504464709&matchtime=1602

I've also had it happen multiple times with Quill Spray and its granted ability Hairball in match: matchid=6508193444&matchtime=1438

When the Aghs upgrade is received, the extra ability shows up at the end of the ability bar, with no keybind. Right clicking it or toggling auto-cast on its matching ability (as you're supposed to for these abilities in AD) will cause the base ability to move to the end of the ability bar and lose its' keybind. 

Very frustrating to play a game with Quill Spray having to spam click it the entire game.

**Comment by Dagsss** [comment]
> This happens with several other abilities where Aghs scepter/shard grants an additional ability.
> 
> I've had it happen with Death Pulse and its granted ability Deathseeker in match: matchid=6504464709&matchtime=1602
> 
> I've also had it happen multiple times with Quill Spray and its granted ability Hairball in match: matchid=6508193444&matchtime=1438
> 
> When the Aghs upgrade is received, the extra ability shows up at the end of the ability bar, with no keybind. Right clicking it or toggling auto-cast on its matching ability (as you're supposed to for these abilities in AD) will cause the base ability to move to the end of the ability bar and lose its' keybind.
> 
> Very frustrating to play a game with Quill Spray having to spam click it the entire game.

The Death Pulse one also happened to me, once. Problem is I didn't read that I can toggle the ability to use Death Seeker. I am not entirely sure if the case is the same with this Gobble Up and Spit Out, as I just reported this on behalf of our TB because I was quite sure that he will not report this here nor in the AD subreddit. I see him pinging the abilities multiple times, but I haven't asked him if he right clicked it or not.
