### ISSUE TITLE
Dota Plus Live spectate bug

### ISSUE THREAD

**Issue by KarthickEka** [jeffhill/Dota2#727]
### Description

When I start spectating my friend's game it shows the middle lane only unless i manually move my mouse around. The hero perspective doesn't work until the hero dies and respawns in (some cases). 

### Screenshots

https://youtu.be/gbAhnUXspsA

**Comment by BeeeQueue** [comment]
Duplicate of #5

**Comment by KarthickEka** [comment]
My bad. Closing it.
