### ISSUE TITLE
[Weather] Spring Weather (Missing pink petals).

### ISSUE THREAD

**Issue by Astiberon** [jeffhill/Dota2#758]
### Cosmetic Item Name

Weather Spring 

### Description

Spring weather does not work correctly, only the lighting of the map changes, but there is no effect of falling pink leaves

### Example Match ID

-

### Screenshots

![image](https://user-images.githubusercontent.com/107125193/172639099-0cc30322-ee48-42b6-b28c-c024069a0031.png)
Then:
![image](https://user-images.githubusercontent.com/107125193/172639393-2d18a9e6-93b5-45e6-80bb-a8332d03dcb1.png)
Now:
![image](https://user-images.githubusercontent.com/107125193/172639518-eecab426-e89d-4b0b-b0e8-ec3ed5c34282.png)

**Comment by Cymen90** [comment]
Already posted in #429

At least that is the most upvoted thread covering the issue. Please close this one and give that one an upvote instead <3
