### ISSUE TITLE
Morphling 2 Waveform Charges 25 talent sometimes displays wrong number

### ISSUE THREAD

**Issue by PatRibas** [jeffhill/Dota2#830]
### Hero and spell

Morphling, Waveform

### Description

Some talents, such as Morphling's level 25 talent for 2 Waveform Charges, at times display wrong numbers. In my experience the number is different per game, different per user (talking to people in game, they see different numbers) and appears only some of the time. I have had this happen on Linux on my machine as well as on Windows on other people's machines, so it is not OS-related. I have seen this error on other talents with numbers but not documented it.

### Screenshots

Here is a clip of it happening on qojqva stream: https://clips.twitch.tv/FaintYawningPassionfruitCoolCat-d3vF-AQBza20LLKr

**Comment by pontuslaestadius** [comment]
There are already several issues which try to cover this tooltip issue: #114, #92, #722, #572, and more.

Probably best to close and add any reproduction instructions to whichever is most popular.
