### ISSUE TITLE
Nether Swap works through Eul's when targeted (not cast!) before Eul's is activated

### ISSUE THREAD

**Issue by BrosBe4Codes** [jeffhill/Dota2#836]
### Ability name

Nether Swap

### Description

When Vengeful Spirit targets a hero with Nether Swap before they use Eul's and then walks into cast range while someone is already under the effect of Eul's they will still get swapped. Mind you, Venge cannot target heros in Eul's so this only works if she already targeted someone before they used Eul's. Maybe I missunderstand how this interaction is supposed to function, but in my mind Eul's should entirely prevent being affected by Nether Swap and simply not allow it to be cast on the hero

https://user-images.githubusercontent.com/107108369/172710948-1ba14de4-b22b-42f4-b0b0-d856265f2bb7.mp4

### Example Match ID (and possibly Timestamp)

6608058161 - 34:00

**Comment by Astiberon** [comment]
> Venge cannot target heros in Eul's

You can target heroes affected by Eul. Raise the cursor higher, directly on the hero, and not under him.
![image](https://user-images.githubusercontent.com/107125193/172713753-eb04c8d0-0ee6-4ac8-8214-42164a18ea20.png)

**Comment by Bu3nyy** [comment]
Nether Swap can target invulnerable units. This is intended since 7.23.

**Comment by BrosBe4Codes** [comment]
> You can target heroes affected by Eul. Raise the cursor higher, directly on the hero, and not under him.

The more you know. Still unsure though if it should work in the first place. Seems a little random to have very specific spells able to be targeted and used through Eul's. Like Oracle's Fortune's End.
