### ISSUE TITLE
7.31d - Dark Seer Vacuum (lvl1) does 10 damage instead of 100

### ISSUE THREAD

**Issue by SumantBagri** [jeffhill/Dota2#859]
[7.31d_darkseer.zip](https://github.com/jeffhill/Dota2/files/8865912/7.31d_darkseer.zip)

Snippet from the patch notes
![image](https://user-images.githubusercontent.com/19651367/172742820-eb9f4e55-3040-4041-a2ac-85e78e23d718.png)

**Comment by hansong1994** [comment]
This is fixed 15 minutes ago.
