### ISSUE TITLE
[Sniper] Full-Bore bonanza equipped when using the immortal effect with other cape

### ISSUE THREAD

**Issue by angelaraya** [jeffhill/Dota2#868]
### Cosmetic Item Name

Full-Bore Bonanza

### Description

When using the Full-Bore bonanza headshot effect (quak!) with a different cape the item is shown on the hero when a skill point is assigned to the spell.

### Example Match ID

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/57408730/172744932-242421fb-4a95-4142-a453-363c676ff8bc.png)

**Comment by evilmtv** [comment]
I have this equipped
![image](https://user-images.githubusercontent.com/19277738/172919988-5454aed8-e062-4182-b046-dc3a03e9569d.png)

Selected Full-Bore Bonanza immortal effect
![image](https://user-images.githubusercontent.com/19277738/172920060-419a8717-b89d-4740-9a66-3768686afd14.png)

Now I effectively have 6 immortals equipped!
![image](https://user-images.githubusercontent.com/19277738/172920308-f3a6d505-bcb5-4368-b47c-8b4da9d2539f.png)

Stonks, pls don't fix.

**Comment by evilmtv** [comment]
Damn it got fixed.
Full-Bore Bonanza cape is no longer shown (tested both in demo and actual game) while the Full-Bore Bonanza's effect works as expected.

Suggesting this issue get closed @jeffhill
Could you confirm this for your set too @angelaraya ?
