### ISSUE TITLE
Game crashes when opening any treasure page or hero loadout

### ISSUE THREAD

**Issue by Chokerino** [jeffhill/Dota2#872]
### Description

As the title states basically. Don't see any other posts related to this so I'm not sure what the problem is. On windows 11 and using dx11. It does not occur on vulkan though. What other information is needed to diagnose it?

**Comment by andryij** [comment]
Looks like I have similar issue. After recent update, first it crashed after pick phase ended. I couldn't reconnect (crashed during loading). It now crashes every time on hero loadout. I deleted all files and redownloaded, didn't help.

After enabling vulkan problem doesn't exist anymore

**Comment by Chokerino** [comment]
@andryij I updated the nvidia drivers and it seems to have fixed this
