### ISSUE TITLE
Changing Immortal Effect Changes ENTIRE Item for Featured Heroes.

### ISSUE THREAD

**Issue by Enivoke** [jeffhill/Dota2#876]
### Cosmetic Item Name

Any cosmetic

### Description

Here is a video demoing one hero that i noticed because its my featured hero in dota 2.
https://youtu.be/uKLo_hVEi3M
if you need any questions, feel free to ask.

### Example Match ID

none

### Screenshots

https://youtu.be/uKLo_hVEi3M

**Comment by throwaway4bugs** [comment]
Adding this [link](https://github.com/jeffhill/Dota2/issues/864#issue-1265473778) because it's the same one as explained in the description.

**Comment by Enivoke** [comment]
> Adding this [link](https://github.com/jeffhill/Dota2/issues/864#issue-1265473778) because it's the same one as explained in the description.

Thanks, totally missed that. It's the same issue indeed.

**Comment by throwaway4bugs** [comment]
FYI this issue has been fixed, not sure when but it is fixed on the live version. Thanks
