### ISSUE TITLE
The game is stuck in the same place for a year and a half now

### ISSUE THREAD

**Issue by archivariouss** [jeffhill/Dota2#890]
### Description

After continuous time of playing dota, I love this game and it’s so sad that game is stuck now. What is this 7.31d? Where’s Chaos Knight nerf? Pugna? Where’s at least one or two global changes? Map rework? Maybe delete outpost already? Delete refresher? Every game is the same scenario: do the lining stage, fight for easylane tower, farm and loooooooong roshan hide-and-seek. Seriously, a lot of my friends are just losing interest because despite having 120+ heroes game lost the concept of economic strategy. There’s almost no strategy anymore and economy is bad(in my opinion, but not the major issue)

WHERE’S THE GLOBAL CHANGES?

**Comment by aroccarian** [comment]
Not a bug. Please close.

**Comment by AmanovAkbar** [comment]
I feel you bro.
