### ISSUE TITLE
Stop writing player IDs into server_log.txt when a match is accepted

### ISSUE THREAD

**Issue by xdugyx** [jeffhill/Dota2#897]
There is no need to VAC ban the overwolf app.

All you have to do is stop writing the player IDs to the server_log.txt file in the folder SteamLibrary\steamapps\common\dota 2 beta\game\dota

It gathers the player IDs through that file. Whenever you accept a match the Dota client writes the Match ID and all player IDs into that file.

**Comment by BlueHammer** [comment]
Upvote this. Players should remain anonymous until picking phase is totally over.

**Comment by jeffhill** [comment]
This will be fixed in the next hotfix - we won't write anything to server_log.txt anymore. Thanks for the bug report!

**Comment by BlueHammer** [comment]
> This will be fixed in the next hotfix - we won't write anything to server_log.txt anymore. Thanks for the bug report!

El Jefe please fix this Earth Spirit bug :(
https://github.com/jeffhill/Dota2/issues/336

**Comment by somethingxful49** [comment]
This has been included in today's hotfix! https://www.reddit.com/r/DotA2/comments/vcgvff/todays_hotfix/

**Comment by BlueHammer** [comment]
> This is not a good change.
> 
> Ranked matchmaking is the closest to a competitive environment most players will ever get to play. Having information hidden (as most players choose nowdays) also gives asymmetric benefits. Here are a couple of points I'd like to point out:
> 
>     1. Players that opt to play cores also generally get to pick last. With match history data being hidden, this opens up for very important lastpicks that can go unpunished. This entirely breaks the balance of the game - suppose a professional team is very successful with a niche hero. Most opposing teams will opt to ban OR prepare to beat it in advance. For pub matches, we should **at least** have an insight into such picks to prepare accordingly.
> 
>     2. Certain of aforementioned heroes have very different playstyle and warp the way the game is played entirely. Some of these include Brood Mother, Tinker, Arc Warden, Lone Druid and so on (I am sure those more proficient at the game will understand what I mean by this). Having access to these niche picks without worrying about a ban can inflate players' ratings and when those heroes are banned, they will play significantly worse because the entire play pattern is different. This, again, introduces uncertainty and instability to matches.
> 
>     3. While smurfing is a nother separate issue, let's assume that smurfing exists. It is very important to identify smurf players in pregame, as it heavily impacts the decision making in the draft and playstyle. It would also make the process of eliminating smurfs with community's help possible.
> 
> 
> I would like someone on the development team to consider these points. There are things that are easy (doing what most of the community wants) and there are things that are right. Perhaps it might initially feel like a good idea to improve anonimity, but if we take competitive or inhouse leagues for any merit, it's crucial to know a person's match history. It is the same for ranked matchmaking.
> 
> If a player choses to hide their history, only their unranked match data should be hidden (for the purpose of practice and strategy development).

All your argument points to niche situations (ie. being pro, meeting smurf, etc.). In most cases, the most balanced situation is to have 5 anonymous players vs 5 anonymous players where drafting is purely based on hero matchup rather than which players can play what hero. Secondly, even if what you arguing is correct, it is still largely unfair to the 80% of players who don't use overwolf at all.

So no, keep it removed dev.

**Comment by anko** [comment]
> [...] the devs should make this an in-game feature. You should 100% be able to have a quick glance overview of every players recent games.

What about privacy? Many players have their profile set to private.

- Showing their history anyway would disrespect that setting, potentially put people in danger due to stalkers etc., and raise legal concerns in the EU. I don't think that is acceptable.
- If private profiles' matches _aren't_ shown but others are, then we would have many matches with information asymmetry, with more of one team's players than the other's choosing to make their history private. It would be unfair, and incentivise players to turn their profiles private, not because they want to, but because it maximises win chances.

Since both options are bad, I think the solution implemented here (of all history being hidden during pick) is fine. Everyone is on an even playing field, profile privacy settings are respected, and having a public or private match history does not affect win chances.

**Comment by Manuel-ReyGallard** [comment]
Last picks are part of the game balance. Showing/hiding match history doesn't prevent a huskar/brood/arc/meepo last pick when there are no counters. It just shows you who spams a certain hero.

The most balanced way to play pubs is the have the players information hidden. If you want to have a different approach to the picking phase you can play Captain's Mode where there are strategy phases and bans in-between picks.

**Comment by apollorust** [comment]
> * Showing their history anyway would disrespect that setting, potentially put people in danger due to stalkers etc., and raise legal concerns in the EU. I don't think that is acceptable.

It's already public and not personal data, thus not a legal problem.

I don't get these changes, why make it harder if it's still possible? Overwolf dev said fix is ready in 2-3 days. They should either not show the player information until after picking phase has completed or just keep offering the data easily. What these changes do at best is to give cheaters even more advantage.

This change is also a major example of why game devs shouldn't listen to their community, one-trick ponies now got their will at least for a few days on an extremely controversial thing. What will happen the next time they get loud enough?

**Comment by schoerg** [comment]
It's a bugfix.

**Comment by drusepth** [comment]
> This is not a good change.
> 
> Ranked matchmaking is the closest to a competitive environment most players will ever get to play. Having information hidden (as most players choose nowdays) also gives asymmetric benefits. Here are a couple of points I'd like to point out:
> 
> 1. Players that opt to play cores also generally get to pick last. With match history data being hidden, this opens up for very important lastpicks that can go unpunished. This entirely breaks the balance of the game - suppose a professional team is very successful with a niche hero. Most opposing teams will opt to ban OR prepare to beat it in advance. For pub matches, we should **at least** have an insight into such picks to prepare accordingly.
> 2. Certain of aforementioned heroes have very different playstyle and warp the way the game is played entirely. Some of these include Brood Mother, Tinker, Arc Warden, Lone Druid and so on (I am sure those more proficient at the game will understand what I mean by this). Having access to these niche picks without worrying about a ban can inflate players' ratings and when those heroes are banned, they will play significantly worse because the entire play pattern is different. This, again, introduces uncertainty and instability to matches.
> 3. While smurfing is a nother separate issue, let's assume that smurfing exists. It is very important to identify smurf players in pregame, as it heavily impacts the decision making in the draft and playstyle. It would also make the process of eliminating smurfs with community's help possible.
> 
> I would like someone on the development team to consider these points. There are things that are easy (doing what most of the community wants) and there are things that are right. Perhaps it might initially feel like a good idea to improve anonimity, but if we take competitive or inhouse leagues for any merit, it's crucial to know a player's match history. It is the same for ranked matchmaking.
> 
> If a player choses to hide their history, only their unranked match data should be hidden (for the purpose of practice and strategy development).

These are all very good reasons to implement Overwolf functionality into the game directly, but relying on users to download a third-party app to "level the playing field" inherently does the opposite for those who are unwilling or unable to run untrusted third-party applications that may or may not put their account at risk for a VAC ban.

If Overwolf's features are important, they should be added to the game. As is, they give some players an unfair advantage and often make the game less fun at most brackets. Banrates for my most-played hero dropped from (approximately) a ban-every-three-games to a ban-every-27-games when I made my profile private (and my winrate increased from 52% to 53%); I'd love to make my profile public again, but the benefits of doing so are not worth being unable to play my favorite hero(es) in most of my games.

**Comment by eVen-gits** [comment]
> These are all very good reasons to implement Overwolf functionality into the game directly, but relying on users to download a third-party app to "level the playing field" inherently does the opposite for those who are unwilling or unable to run untrusted third-party applications that may or may not put their account at risk for a VAC ban.

Agreed. As someone outlined above, the problem with current "fix" is it's still possible to get player IDs, but it's just harder. If anything, this is only worse if anything. Either make it accessible or don't.

I think it should be accessible and it should be accessible easy and to everyone, without third party solutions.

> If Overwolf's features are important, they should be added to the game. As is, they give some players an unfair advantage and often just make the game less fun in many brackets. Banrates for my most-played hero dropped from (approximately) a ban-every-three-games to a ban-every-27-games when I made my profile private (and my winrate barely moved from 52% to 53%); I'd love to make my profile public again, but the benefits of doing so are not worth being unable to play my favorite hero(es) in most of my games due to Overwolf existing.

I think people don't understand the difference between data and information and assisted models. Having match history and heroes is one thing, but having access to automated suggestions is something else and that part should be discouraged. However, I don't think that can be prevented for as long as third party solutions work.

So the real question is - is it realistic to expect ingame player overview (I think this was initially promised with reborn launch) and if so, once it's done, it might be reasonable to discontinue apps like overwolf.

I don't see a reason why not even open the panorama UI configs and make a workshop page for different configurations to present data available in the client. Much like a "guide". It's just that is uses players' match data and aggregates it into a visual representation that you can see and then make informed decisions on during draft.

**Comment by CGK368** [comment]
I think a great solution would be:
At the start, let everyone vote for the ban of two heroes (20 in total), after which the system will ban A. A random half of these heroes B. priority of the heroes with the most votes (example: first Bane 3 votes, after Tinker 2 votes and Pudge 2 votes, the rest of the heroes received 1 vote each, each player has 2 votes, in total 20 votes per ban, there are 13 heroes left with one vote, of which DotA will randomly select the remaining 7)
Next comes the pick of two heroes from each team
After that, the remaining 6 players again 'vote' to ban 'N' heroes, or ban one hero each and pick two more heroes
At the end, 1-2 bans are made by the last two players from each team and they themselves take the heroes

(The number of bans at the start in such a system can be reduced from 10 to 4 as in CM)

**Comment by maplepy** [comment]
> * raise legal concerns in the EU

that's not how it works buddy
