### ISSUE TITLE
Eul's and Invoker tornado reposition Roshan to center of the map

### ISSUE THREAD

**Issue by shubhrathi** [jeffhill/Dota2#903]
### Item name

Eul's scepter of divinity

### Description

Apparently euls reposition the roshan to the centre of the map

https://user-images.githubusercontent.com/12682588/172773105-87a530e4-ca33-4486-9f0b-a7d23bf1ce93.mp4

### Example Match ID and Timestamp

6608482781 23:00 game time

edit: same thing happens with invoker tornado also

**Comment by aroccarian** [comment]
Consider entering a title for the post to make it easier to find/track.

**Comment by shubhrathi** [comment]
> Consider entering a title for the post to make it easier to find/track.

Done

**Comment by opomuc** [comment]
@shubhrathi why did you close it? was it fixed?

**Comment by shubhrathi** [comment]
Yes in recent patch it is fixed. https://www.reddit.com/r/DotA2/comments/v919b9/dota_2_update_for_late_6922_61022/?utm_medium=android_app&utm_source=share

**Comment by shubhrathi** [comment]
> @shubhrathi why did you close it? was it fixed?

Yes in recent patch it is fixed. https://www.reddit.com/r/DotA2/comments/v919b9/dota_2_update_for_late_6922_61022/?utm_medium=android_app&utm_source=share
