### ISSUE TITLE
!s:value issues with Morph and Riki

### ISSUE THREAD

**Issue by LokeLok** [jeffhill/Dota2#92]
Morph's 10(left), 25(right) and Riki's 20(left) talent shows !s:value or pulls a random number from somewhere.

**Comment by LokeLok** [comment]
![morph](https://user-images.githubusercontent.com/106764092/171701826-26514247-3ea5-4554-a577-9a4fb1ccdf3f.png)
![Uploading riki.png…]()

**Comment by LokeLok** [comment]
![riki](https://user-images.githubusercontent.com/106764092/171702270-d8e5d18d-8f90-423a-973c-6d7874add439.png)

**Comment by aharonk** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/13606487/171732093-9bcd3b10-55ac-4924-b379-60044fa99074.jpg)

**Comment by MrMooEar** [comment]
It looks like the Riki issue was already fixed.
Just fixed the 2x Morph talents. Should be out with the next update! 👍
