### ISSUE TITLE
Watch In-game live button not working

### ISSUE THREAD

**Issue by Poodlescray** [jeffhill/Dota2#923]
### Description

I'm not able to view any live games in the watch tab, it says "waiting to watch game..." for a minute then after a minute "Could not watch this game at this time" comes up. Happening to any live game I try to view.
Watching live games from the friends list is possible, so only watch live tab isn't working.

**Comment by crastril** [comment]
same issue here after loading for a few minutes
![image](https://user-images.githubusercontent.com/107172559/172853926-e08f5638-eb57-46c6-bd89-532630ea2aa9.png)

**Comment by Rmin-Sadigh** [comment]
Watch game works for people in the friend list, but nothing from the watch tab. Pro pubs have at most 10-15 viewers (most likely their friends), so the issue has affected everyone.

**Comment by notr1ch** [comment]
I noticed the dialog gets stuck if there is this response from the server:
```
[GCClient] Recv msg 7092 (k_EMsgGCWatchGameResponse), 19 bytes
Received CMsgWatchGameResponse result 0.
```

**Comment by unkndld** [comment]
> I noticed the dialog gets stuck if there is this response from the server:
> 
> ```
> [GCClient] Recv msg 7092 (k_EMsgGCWatchGameResponse), 19 bytes
> Received CMsgWatchGameResponse result 0.
> ```

Same here.

**Comment by tick373** [comment]
I am having the exact same issue as OP.

**Comment by deathkiller1** [comment]
Can't play the game due to micro stutters, can't watch pub games.. great patch.. I'm not sure why this bug isn't fixed, it's a simple permission issue

**Comment by deathkiller1** [comment]
Sorry if i came out to be a bit rude earlier..i just felt this watch dota tv bug was a simpler fix.. And this was required for the end users to check their network stability
