### ISSUE TITLE
[7.31d] Storm Spirit unmentioned changes

### ISSUE THREAD

**Issue by porottaja** [jeffhill/Dota2#928]
### Ability name

Ball Lightning, and Overload Shard

### Description

Bonus attack speed from Overload shard and the manacost for Ball Lightning were changed with no mention in patch notes.

![storm_spirit_731d](https://user-images.githubusercontent.com/13699929/172827568-a9b5821f-cf22-45d7-8584-04beb658cb0e.png)

### Example Match ID (and possibly Timestamp)

Patch notes

**Comment by DarkoniusXNG** [comment]
https://steamdb.info/patchnotes/8914797/
This can be closed.
