### ISSUE TITLE
When spectating a game with assisted camera enabled, Spectator Camera movement is disabled.

### ISSUE THREAD

**Issue by Pimpmuckl** [jeffhill/Dota2#940]
### Description

Since the 7.31d update, moving the camera while having assisted camera is enabled is not possible.

**Steps to reproduce:**
1. Load into a DotaTV game or be in broadcaster or spectator slot in a lobby
2. Enable `dota_toggle_assisted_camera_operator`

**Expected behaviour:**
The keys bound to `Spectator Camera Forward/Back/Left/Right`, often `W, S, A, D` or `Arrow Up, Down, Right, Left` move the camera.

**Actual behaviour:**
The keys bound to `Spectator Camera Forward/Back/Left/Right`, often `W, S, A, D` or `Arrow Up, Down, Right, Left` have no effect.

**Workaround**
For people casting/observing matches right now, I would suggest making a bind to quickly disable the assisted camera and using smooth drag to observe large fights.

To select different heroes, tap the number key once for selection and another time for camera moves to that hero.

**Comment by eddieparker** [comment]
This should be fixed in the next update.  Thanks for the clear repro steps!

**Comment by Pimpmuckl** [comment]
Update after testing just now:

1. S and W are inverted with `dota_toggle_assisted_camera_operator` on compared to off.

2. The behaviour of pre-patch assisted camera is not identical to post-patch.
This is a bit hard to describe. Pre-7.31d, using camera buttons with assisted camera on had more elasticity than using them without assisted camera. So it was not a full overwrite but more of a "nudge" in a certain direction.

We're between DPC games right now, so I'll try to update the description tomorrow with more details to help.

**Comment by eddieparker** [comment]
I'll look into the inversion.

Can you play with the convar "dota_camera_assisted_camera_operator_movement_multiplier" to find a number that felt more representative of the speed you had before?

**Comment by Pimpmuckl** [comment]
Thanks about the inversion!

I tested a little bit just now and I believe `dota_camera_assisted_camera_operator_movement_multiplier 2400` feels really good and pretty much identical to pre-7.31d.

**Comment by eddieparker** [comment]
OK, fixed, and 2400 is the new default.  Thanks again for filing the bug.
