### ISSUE TITLE
CK Immortal Chaos Fulcrum 

### ISSUE THREAD

**Issue by shaileshgarg** [jeffhill/Dota2#959]
### Cosmetic Item Name

Chaos Fulcrum

### Description

In Hero View the Immortal Item has a strange effect.

### Example Match ID

-

### Screenshots

https://user-images.githubusercontent.com/26450759/172875397-60e6b95e-365a-4a80-a9c9-23a41090296b.mp4

**Comment by Astiberon** [comment]
I don't have this problem. What graphics settings do you have, and did you change them in the process?

**Comment by shaileshgarg** [comment]
I have all setting on Ultra and checked boxes for all Additional Video Setting.

**Comment by shaileshgarg** [comment]
Fiddled with the setting, now its even strange

https://user-images.githubusercontent.com/26450759/172879962-3c3aabe4-872d-4f50-9fcf-9e662c8fbc0a.mp4

.

**Comment by Astiberon** [comment]
What rendering are you using Vulcan or DX 11?

**Comment by shaileshgarg** [comment]
> What rendering are you using Vulcan or DX 11?

DX11

**Comment by shaileshgarg** [comment]
Lowering the graphics to low and then high again fixed the issue.
