### ISSUE TITLE
Hero moves with stutter.

### ISSUE THREAD

**Issue by anupchand** [jeffhill/Dota2#965]
### Description

After the new update 7.31d
1. Hero moves with a micro-stutter. It is not a constant periodic stutter but it kicks in randomly. Cannot move around creeps, units, or trees gracefully due to sudden micro freezing while trying to move the hero.
2. Also cannot last hit properly due to improper micro-freezes.
3.  The game gets laggy with respect to time.
4. During ganks the above issues are more noticeable

### Example Match ID (and possibly Timestamp)

6608592641, 6609241941, 6608717153

**Comment by opomuc** [comment]
yeah. @anupchand please close this one. 

#915 has more info on the issue
