### ISSUE TITLE
Player Perspective centers on midlane

### ISSUE THREAD

**Issue by AjBurn** [jeffhill/Dota2#97]
In replays when using the Player Perspective camera view, the camera will always recenter on the middle lane. I've had several friends confirm this as well.

**Comment by Yoho11** [comment]
A few details from my experience:
I noticed this issue only when spectating the game live, and not with the delay.
It doesn't happen every time and I had situations where it fixed after some time in  the game.
Closing the spectate and starting again wouldn't fix it.

**Comment by opomuc** [comment]
Looks like a duplicate of #5

**Comment by AjBurn** [comment]
> Looks like a duplicate of #5

Shoot I looked through all but the ones that were already closed. My bad!
