### ISSUE TITLE
"Status Effects" tutorial scenario is broken

### ISSUE THREAD

**Issue by rayningforests** [jeffhill/Dota2#978]
### Description

After stunning Shadow Shaman with Abyssal Blade, Lina kills SS. After this nothing happens regardless of what you do.

### Screenshots

![image](https://user-images.githubusercontent.com/85694201/172921343-00f4f6a5-9daa-4105-ac8e-d9674d832f55.png)

**Comment by Gutzcode** [comment]
Patch 7.31D broke several of the tutorials #1005 Covers this and more of the tutorial bugs. Should be merged as one.

**Comment by rayningforests** [comment]
moving issue to [#1005](https://github.com/jeffhill/Dota2/issues/1005)
