### ISSUE TITLE
QOL: Please start counting the turbo games

### ISSUE THREAD

**Issue by Usera2** [jeffhill/Dota2#979]
### Description

For example hero's win and lose count and stats for inscribed gems.
In the past 2-3 years i only have played turbo games, but since turbo stats doesn't get recorded, the heroes play counts or stats like  first blood or rampage have not been changed in this time.
It doesn't matter if there is a second set of records for them, but still it would be nice to be recorded in the profile.

Also from New dota+ update, battle report only has data for normal games. So for turbo players like me it's just an empty page without any use.

**Comment by Daar543** [comment]
Most of the stuff, which counts turbo stats, is counted as half values. I guess this one should too.

**Comment by Usera2** [comment]
Related to
#917 
#847

**Comment by opomuc** [comment]
@Usera2 it not related. it is a duplicate. in order to remove clutter please close this one

**Comment by Usera2** [comment]
> 

yep, you are right. i didn't notice it earlier
