### ISSUE TITLE
drow ranger reaper's wreath immortal bug interaction with arcana

### ISSUE THREAD

**Issue by teglaservin** [jeffhill/Dota2#986]
### Item name

cosmetic item reaper's wreath

## Expected Behavior
Upon equipping Drow Ranger's Reaper's Wreath immortal weapon cosmetic as an "Effects-only" slot for her ultimate Marksmanship, this adds the marksmanship proc projectile effect upon getting a proc; while not altering the model of her weapon whatsoever, whichever model it is.

## Current Behavior
Upon equipping Drow Ranger's Reaper's Wreath immortal weapon cosmetic as an "Effects-only" slot for her ultimate Marksmanship, if one equips her arcana item Dread Retribution on her weapon slot, the two weapon models get overlapped, with the model for Reaper's Wreath occasionally floating to the side, and mostly floating on top, overlayed onto the crossbow of the arcana.

## Possible Solution
Do not alter the weapon model by equipping the immortal, as it should not be part of the "Effects and particles" of the immortal.

## Steps to Reproduce
1. Equip Reaper's Wreath into the marksmanship effect slot using the corresponding dropdown menu in the loadout section
2. Equip Dread Retribution on the weapon slot in the loadout section
3. Enter a game
4. Bug is immediately visible without other steps to reproduce

### Example Match ID and Timestamp

6609750735

**Comment by arthurnalves** [comment]
duplicate, please close
