### ISSUE TITLE
Weird pink effect

### ISSUE THREAD

**Issue by sheydisend** [jeffhill/Dota2#988]
### Cosmetic Item Name

 Dota+ summer landscape

### Description

Weird pink effect on screen edges when using Dota+ summer landscape. There is no effect when using the default landscape. Is that how it was intended or its new Dota+ update feature?
It's really distracting at times...

### Example Match ID

787878787878787

### Screenshots

![загружено](https://user-images.githubusercontent.com/107221214/172950050-ffbf2865-27e5-4a53-8c81-7fc4956666cd.jpg)

**Comment by opomuc** [comment]
hi @sheydisend see #972. try disabling Summer Terrain before matchmaking.

also please close the issue since it is a duplicate

**Comment by sheydisend** [comment]
@opomuc ty
