### ISSUE TITLE
Butterflies remain after Rubick casts Nature's Attendants

### ISSUE THREAD

**Issue by danielsegge** [jeffhill/Dota2#998]
### Ability name

Spell steal, Nature's Attendants

### Description

Animation of butterflies flying around Rubick remains after the duration of Nature's Attendants ends. Happens just after 25 minutes on the game clock. Turbo mode.

### Example Match ID (and possibly Timestamp)

6609973061

**Comment by TheUnholyWrath** [comment]
This has already been included in #561 . Please close this
